begin;
create function public.operations_materials(p_organization_id uuid,p_project_id uuid,p_area_id uuid default null,p_page integer default 1) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare rows jsonb;total bigint;begin
 if not private.ops_access(p_organization_id,'inventory.view',p_project_id) or not private.ops_access(p_organization_id,'execution.view',p_project_id) or p_project_id is null then raise exception 'Unavailable project material report' using errcode='42501';end if;
 if p_area_id is not null and not exists(select 1 from public.project_areas where organization_id=p_organization_id and project_id=p_project_id and id=p_area_id) then raise exception 'Unavailable area' using errcode='42501';end if;
 if p_page is null or p_page not between 1 and 10000 then raise exception 'Invalid page' using errcode='22023';end if;
 with estimates as (
 select l.variant_id,l.purchase_unit unit,sum(l.base_quantity::numeric/nullif((l.calculation_snapshot#>>'{conversion,consumption_per_purchase}')::numeric,0)) estimated,sum(l.waste_quantity::numeric/nullif((l.calculation_snapshot#>>'{conversion,consumption_per_purchase}')::numeric,0)) waste,sum(l.planned_purchase_quantity::numeric) planned
 from public.execution_estimates e join public.execution_estimate_lines l on l.revision_id=e.current_approved_revision_id join public.execution_estimate_scope_items s on s.id=l.scope_id where e.organization_id=p_organization_id and e.project_id=p_project_id and l.variant_id is not null and s.coverage='estimated' and (p_area_id is null or s.area_id=p_area_id) group by l.variant_id,l.purchase_unit),
 ordered as (select i.variant_id,i.unit,sum(i.quantity::numeric) quantity from public.purchase_orders p join public.purchase_order_items i on i.po_id=p.id where p.organization_id=p_organization_id and p.project_id=p_project_id and p.status in ('issued','partially_received','received','closed') and i.variant_id is not null group by i.variant_id,i.unit),
 received as (select i.variant_id,i.unit,sum(g.received_quantity::numeric) received,sum(g.accepted_quantity::numeric) accepted,sum(g.rejected_quantity::numeric) rejected from public.goods_receipts r join public.goods_receipt_items g on g.receipt_id=r.id join public.purchase_order_items i on i.id=g.po_item_id where r.organization_id=p_organization_id and r.project_id=p_project_id and i.variant_id is not null group by i.variant_id,i.unit),
 activity as (select lot.variant_id,lot.unit,
 sum(case when t.kind='issue_to_site' and m.location_id=t.destination_location_id then m.quantity::numeric else 0 end) issued,
 sum(case when t.kind='consumption' then -m.quantity::numeric else 0 end) consumed,
 sum(case when t.kind='return_from_site' and m.location_id=t.destination_location_id then m.quantity::numeric else 0 end) returned,
 sum(case when t.kind='scrap' then -m.quantity::numeric else 0 end) scrapped,
 sum(case when t.kind='damage' then -m.quantity::numeric else 0 end) damaged
 from public.inventory_transactions t join public.inventory_movements m on m.transaction_id=t.id join public.inventory_lots lot on lot.id=m.lot_id where t.organization_id=p_organization_id and t.project_id=p_project_id and t.kind<>'reversal' and not exists(select 1 from public.inventory_transactions r where r.kind='reversal' and r.original_transaction_id=t.id) and (p_area_id is null or t.area_id=p_area_id) group by lot.variant_id,lot.unit),
 site as (select lot.variant_id,lot.unit,sum(m.quantity::numeric) quantity from public.inventory_movements m join public.inventory_locations loc on loc.id=m.location_id join public.inventory_lots lot on lot.id=m.lot_id where m.organization_id=p_organization_id and loc.site_project_id=p_project_id group by lot.variant_id,lot.unit),
 store as (select lot.variant_id,lot.unit,sum(m.quantity::numeric) quantity from public.inventory_movements m join public.inventory_locations loc on loc.id=m.location_id join public.inventory_lots lot on lot.id=m.lot_id join public.goods_receipt_items gi on gi.id=lot.receipt_item_id join public.goods_receipts gr on gr.id=gi.receipt_id where m.organization_id=p_organization_id and gr.project_id=p_project_id and loc.site_project_id is null group by lot.variant_id,lot.unit),
 keys as (select variant_id,unit from estimates union select variant_id,unit from ordered union select variant_id,unit from received union select variant_id,unit from activity union select variant_id,unit from site),
 report as (select k.variant_id,k.unit,v.name material,mat.name material_family,cat.name category,
 trim_scale(round(coalesce(e.estimated,0),6))::text estimated,trim_scale(round(coalesce(e.waste,0),6))::text planned_waste,trim_scale(coalesce(e.planned,0))::text planned_purchase,
 trim_scale(coalesce(o.quantity,0))::text purchased,trim_scale(coalesce(o.quantity,0))::text ordered,trim_scale(coalesce(r.received,0))::text received,trim_scale(coalesce(r.accepted,0))::text accepted,trim_scale(coalesce(r.rejected,0))::text rejected,
 trim_scale(coalesce(a.issued,0))::text issued,trim_scale(coalesce(a.consumed,0))::text consumed,trim_scale(coalesce(a.returned,0))::text returned,trim_scale(coalesce(a.scrapped,0))::text scrapped,trim_scale(coalesce(a.damaged,0))::text damaged,
 trim_scale(coalesce(si.quantity,0))::text at_site,trim_scale(coalesce(st.quantity,0))::text at_store,trim_scale(coalesce(si.quantity,0)+coalesce(st.quantity,0))::text remaining,
 trim_scale(round(coalesce(a.consumed,0)-coalesce(e.estimated,0),6))::text variance,
 trim_scale(greatest(0,coalesce(e.planned,0)-coalesce(a.consumed,0)-coalesce(si.quantity,0)-coalesce(st.quantity,0)))::text shortage,
 trim_scale(greatest(0,coalesce(si.quantity,0)+coalesce(st.quantity,0)-greatest(0,coalesce(e.planned,0)-coalesce(a.consumed,0))))::text potential_surplus
 from keys k join public.material_variants v on v.id=k.variant_id join public.materials mat on mat.id=v.material_id left join public.material_categories cat on cat.id=mat.category_id left join estimates e using(variant_id,unit) left join ordered o using(variant_id,unit) left join received r using(variant_id,unit) left join activity a using(variant_id,unit) left join site si using(variant_id,unit) left join store st using(variant_id,unit))
 select (select count(*) from report),coalesce((select jsonb_agg(to_jsonb(x)) from(select * from report order by category,material,variant_id,unit limit 25 offset (p_page-1)*25)x),'[]') into total,rows;
 return jsonb_build_object('rows',rows,'total',total,'page',p_page,'page_size',25,'basis','All quantities use the explicit purchase unit. Purchased means issued PO commitment, not a vendor bill. Area filtering applies to estimate and recorded usage; procurement and stock remain project totals. Store balances follow project receipt lots and are not reservations.');
end$$;
create function public.operations_costs(p_organization_id uuid,p_project_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare rows jsonb;begin
 if not private.ops_access(p_organization_id,'cost.execution.view',p_project_id) or p_project_id is null then raise exception 'Unavailable operational cost report' using errcode='42501';end if;
 with consumed as(select c.currency,sum(-m.quantity::numeric*c.total_cost::numeric/lot.received_quantity::numeric) amount from public.inventory_transactions t join public.inventory_movements m on m.transaction_id=t.id join public.inventory_lots lot on lot.id=m.lot_id join public.inventory_lot_costs c on c.lot_id=lot.id where t.organization_id=p_organization_id and t.project_id=p_project_id and t.kind='consumption' and not exists(select 1 from public.inventory_transactions r where r.kind='reversal' and r.original_transaction_id=t.id) group by c.currency),
 committed as(select c.currency,sum(c.agreed_amount::numeric) amount from public.subcontractor_work_orders w join public.subcontractor_work_order_costs c on c.work_order_id=w.id where w.organization_id=p_organization_id and w.project_id=p_project_id and w.status not in ('draft','cancelled') group by c.currency),
 certified as(select c.currency,sum(c.amount::numeric) amount from public.work_measurements m join public.work_measurement_costs c on c.measurement_id=m.id where m.organization_id=p_organization_id and m.project_id=p_project_id and m.status='certified' group by c.currency),
 currencies as(select currency from consumed union select currency from committed union select currency from certified)
 select coalesce(jsonb_agg(jsonb_build_object('currency',k.currency,'consumed_material_cost',trim_scale(round(coalesce(co.amount,0),6))::text,'subcontractor_committed_cost',trim_scale(coalesce(cm.amount,0))::text,'certified_work_cost',trim_scale(coalesce(ce.amount,0))::text) order by k.currency),'[]') into rows from currencies k left join consumed co using(currency) left join committed cm using(currency) left join certified ce using(currency);
 return jsonb_build_object('rows',rows,'basis','Source receipt-lot proportional cost; subtotal rounded once to six decimal places. Certified work is not paid work. No accounting profit is calculated.');
end$$;
create function public.operations_closure(p_organization_id uuid,p_project_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb;financial jsonb=null;begin
 if not private.ops_access(p_organization_id,'execution.view',p_project_id) or p_project_id is null then raise exception 'Unavailable project closure' using errcode='42501';end if;
 if private.finance_access(p_organization_id,'financial_report.view') and private.finance_access(p_organization_id,'contract.view') then
 select coalesce(jsonb_agg(jsonb_build_object('contract_number',c.contract_number,'currency',c.currency,'unbilled_value',trim_scale(private.contract_value(c.id)-coalesce((select sum(i.total::numeric) from public.invoices i where i.contract_id=c.id and i.status='issued' and i.invoice_type='tax_invoice'),0))::text,'invoice_outstanding',trim_scale(coalesce((select sum(i.total::numeric-private.invoice_paid(i.id)) from public.invoices i where i.contract_id=c.id and i.status='issued' and i.invoice_type='tax_invoice'),0))::text)),'[]') into financial from public.contracts c where c.organization_id=p_organization_id and c.project_id=p_project_id;end if;
 result=public.operations_dashboard(p_organization_id,p_project_id);
 return result||jsonb_build_object('open_purchase_orders',case when private.execution_access(p_organization_id,'purchase_order.view') then (select count(*) from public.purchase_orders where organization_id=p_organization_id and project_id=p_project_id and status in ('draft','issued','partially_received')) end,'unposted_accepted_receipts',case when private.ops_access(p_organization_id,'inventory.view',p_project_id) then (select count(*) from public.goods_receipts r join public.goods_receipt_items i on i.receipt_id=r.id join public.purchase_order_items pi on pi.id=i.po_item_id where r.organization_id=p_organization_id and r.project_id=p_project_id and i.accepted_quantity::numeric>0 and pi.variant_id is not null and not exists(select 1 from public.inventory_lots l where l.receipt_item_id=i.id)) end,'approved_handovers',(select count(*) from public.handover_records where organization_id=p_organization_id and project_id=p_project_id and status='approved'),'commercial',financial);
end$$;
revoke all on function public.operations_materials(uuid,uuid,uuid,integer),public.operations_costs(uuid,uuid),public.operations_closure(uuid,uuid) from public,anon;
grant execute on function public.operations_materials(uuid,uuid,uuid,integer),public.operations_costs(uuid,uuid),public.operations_closure(uuid,uuid) to authenticated;
commit;
