begin;
create function private.finance_access(org uuid,permission text) returns boolean language sql stable security definer set search_path='' as $$
 select private.has_permission(org,permission) and private.entitled(org,'billing') and (permission not like 'contract.%' and permission not like 'change_order.%' or private.entitled(org,'projects'));
$$;
create function private.finance_require(org uuid,permission text) returns void language plpgsql security definer set search_path='' as $$begin
 perform 1 from public.organizations where id=org for update;
 if not private.finance_access(org,permission) then raise exception 'Forbidden' using errcode='42501';end if;
end$$;
create function private.finance_decimal(value text,signed boolean default false) returns numeric language plpgsql immutable set search_path='' as $$begin
 if value is null or length(value)>40 or value !~ '^-?(0|[1-9][0-9]{0,17})(\.[0-9]{1,6})?$' or (not signed and value::numeric<0) then raise exception 'Invalid decimal' using errcode='22023';end if;
 return value::numeric;
end$$;
create table public.organization_billing_settings(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id),
 version integer not null default 1,legal_name text not null check(length(trim(legal_name)) between 1 and 200),
 billing_address text not null default '' check(length(billing_address)<=2000),tax_identifier text not null default '' check(length(tax_identifier)<=80),
 invoice_prefix text not null default 'INV' check(invoice_prefix ~ '^[A-Z][A-Z0-9-]{0,15}$'),receipt_prefix text not null default 'RCPT' check(receipt_prefix ~ '^[A-Z][A-Z0-9-]{0,15}$'),contract_prefix text not null default 'CT' check(contract_prefix ~ '^[A-Z][A-Z0-9-]{0,15}$'),
 default_terms text not null default '' check(length(default_terms)<=10000),payment_instructions text not null default '' check(length(payment_instructions)<=3000),invoice_notes text not null default '' check(length(invoice_notes)<=3000),receipt_footer text not null default '' check(length(receipt_footer)<=3000),
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id));
create table public.payment_methods(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null check(length(trim(name)) between 1 and 100),kind text not null check(kind in ('cash','bank_transfer','upi','cheque','card_offline','other')),active boolean not null default true,version integer not null default 1,
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,name));
create table public.tax_codes(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),code text not null check(length(trim(code)) between 1 and 80),jurisdiction text not null default '' check(length(jurisdiction)<=100),components jsonb not null check(jsonb_typeof(components)='array' and jsonb_array_length(components)<=8),active boolean not null default true,version integer not null default 1,
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,code));
create table public.contracts(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),customer_id uuid not null,project_id uuid not null,revision_id uuid not null,acceptance_id uuid not null,lead_id uuid,branch_id uuid,
 contract_number text not null,currency text not null check(currency ~ '^[A-Z]{3}$'),precision integer not null check(precision between 0 and 6),original_contract_value text not null check(private.finance_decimal(original_contract_value)>=0),
 source_snapshot jsonb not null,status text not null default 'pending' check(status in ('pending','active','on_hold','completed','closed','cancelled')),version integer not null default 1,accepted_at timestamptz not null,started_at timestamptz,completed_at timestamptz,closed_at timestamptz,cancelled_at timestamptz,status_reason text not null default '',
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,revision_id),unique(organization_id,contract_number),unique(organization_id,id,customer_id,project_id),
 foreign key(organization_id,customer_id,project_id) references public.projects(organization_id,customer_id,id),foreign key(organization_id,revision_id,project_id) references public.quotation_revisions(organization_id,id,project_id),foreign key(organization_id,acceptance_id) references public.quotation_customer_responses(organization_id,id),foreign key(organization_id,lead_id) references public.leads(organization_id,id),foreign key(organization_id,branch_id) references public.branches(organization_id,id));
create table public.payment_schedules(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,label text not null check(length(trim(label)) between 1 and 200),basis_value text not null check(private.finance_decimal(basis_value)>=0),status text not null default 'draft' check(status in ('draft','active','superseded','cancelled')),supersedes_id uuid,version integer not null default 1,activated_at timestamptz,
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,contract_id,id),foreign key(organization_id,contract_id) references public.contracts(organization_id,id),foreign key(organization_id,contract_id,supersedes_id) references public.payment_schedules(organization_id,contract_id,id));
create table public.payment_schedule_items(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,schedule_id uuid not null,label text not null check(length(trim(label)) between 1 and 200),description text not null default '' check(length(description)<=3000),calculation_type text not null check(calculation_type in ('percentage','fixed','remaining')),value text not null check(private.finance_decimal(value)>=0),expected_amount text not null check(private.finance_decimal(expected_amount)>=0),due_trigger text not null default '' check(length(due_trigger)<=300),due_date date,sort_order integer not null check(sort_order between 0 and 199),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,contract_id,id),unique(schedule_id,sort_order),foreign key(organization_id,contract_id,schedule_id) references public.payment_schedules(organization_id,contract_id,id));
create table public.payment_requests(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,schedule_item_id uuid not null,request_number text not null,amount text not null check(private.finance_decimal(amount)>0),due_date date,note text not null default '' check(length(note)<=3000),status text not null default 'issued' check(status in ('issued','void')),document_snapshot jsonb not null,issued_at timestamptz not null default now(),void_reason text,voided_at timestamptz,
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,request_number),foreign key(organization_id,contract_id,schedule_item_id) references public.payment_schedule_items(organization_id,contract_id,id));
create unique index one_live_request on public.payment_requests(schedule_item_id) where status='issued';
create table public.invoices(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,customer_id uuid not null,project_id uuid not null,invoice_number text,invoice_type text not null check(invoice_type in ('proforma','tax_invoice')),currency text not null check(currency ~ '^[A-Z]{3}$'),status text not null default 'draft' check(status in ('draft','issued','void')),version integer not null default 1,issue_date date not null,due_date date check(due_date>=issue_date),tax_mode text not null check(tax_mode in ('exclusive','inclusive')),tax_application text not null check(tax_application in ('line','document')),tax_code_id uuid,tax_snapshot jsonb not null default '[]',place_of_supply text not null default '' check(length(place_of_supply)<=200),billing_state text not null default '' check(length(billing_state)<=200),
 subtotal text not null default '0',discount text not null default '0',taxable_amount text not null default '0',tax_amount text not null default '0',total text not null default '0' check(private.finance_decimal(total)>=0),document_snapshot jsonb,notes text not null default '' check(length(notes)<=3000),terms text not null default '' check(length(terms)<=10000),issued_at timestamptz,issued_by uuid references public.profiles(id),voided_at timestamptz,void_reason text,
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,contract_id,id),unique(organization_id,invoice_number),foreign key(organization_id,contract_id,customer_id,project_id) references public.contracts(organization_id,id,customer_id,project_id),foreign key(organization_id,tax_code_id) references public.tax_codes(organization_id,id));
create table public.invoice_items(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,invoice_id uuid not null,description text not null check(length(trim(description)) between 1 and 3000),quantity text not null check(private.finance_decimal(quantity)>0),unit text not null check(length(unit) between 1 and 80),unit_rate text not null check(private.finance_decimal(unit_rate)>=0),discount text not null default '0',line_amount text not null,taxable_amount text not null,tax_amount text not null,total text not null,tax_code_id uuid,tax_snapshot jsonb not null default '[]',hsn_sac text not null default '' check(length(hsn_sac)<=40),source_type text not null check(source_type in ('manual','milestone','quotation','change_order')),source_id uuid,sort_order integer not null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(invoice_id,sort_order),foreign key(organization_id,contract_id,invoice_id) references public.invoices(organization_id,contract_id,id),foreign key(organization_id,tax_code_id) references public.tax_codes(organization_id,id));
create index invoice_source on public.invoice_items(organization_id,source_type,source_id);
create table public.payments(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,customer_id uuid not null,project_id uuid not null,payment_number text not null,currency text not null,payment_date date not null,amount text not null check(private.finance_decimal(amount)>0),method_id uuid not null,method_snapshot jsonb not null,external_reference text not null default '' check(length(external_reference)<=200),notes text not null default '' check(length(notes)<=3000),idempotency_key uuid not null,request_hash text not null,status text not null default 'recorded' check(status in ('recorded','void')),voided_at timestamptz,voided_by uuid references public.profiles(id),void_reason text,
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,contract_id,id),unique(organization_id,payment_number),unique(organization_id,idempotency_key),foreign key(organization_id,contract_id,customer_id,project_id) references public.contracts(organization_id,id,customer_id,project_id),foreign key(organization_id,method_id) references public.payment_methods(organization_id,id));
create table public.payment_allocations(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,payment_id uuid not null,invoice_id uuid not null,amount text not null check(private.finance_decimal(amount)>0),idempotency_key uuid not null,reversed_at timestamptz,reversed_by uuid references public.profiles(id),reversal_reason text,
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,idempotency_key),foreign key(organization_id,contract_id,payment_id) references public.payments(organization_id,contract_id,id),foreign key(organization_id,contract_id,invoice_id) references public.invoices(organization_id,contract_id,id));
create table public.receipts(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,payment_id uuid not null unique,receipt_number text not null,document_snapshot jsonb not null,status text not null default 'issued' check(status in ('issued','void')),voided_at timestamptz,void_reason text,
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,receipt_number),foreign key(organization_id,contract_id,payment_id) references public.payments(organization_id,contract_id,id));
create table public.change_orders(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,change_order_number text not null,reason text not null check(length(trim(reason)) between 3 and 3000),status text not null default 'draft' check(status in ('draft','issued','approved','rejected','cancelled')),version integer not null default 1,net_adjustment text not null default '0' check(private.finance_decimal(net_adjustment,true) is not null),previous_contract_value text,revised_contract_value text,document_snapshot jsonb,terms text not null default '' check(length(terms)<=10000),issued_at timestamptz,approved_at timestamptz,approved_by uuid references public.profiles(id),approval_evidence text,decision_reason text,
 created_by uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,contract_id,id),unique(organization_id,change_order_number),foreign key(organization_id,contract_id) references public.contracts(organization_id,id));
create table public.change_order_items(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,contract_id uuid not null,change_order_id uuid not null,change_type text not null check(change_type in ('addition','deletion','modification','price_adjustment')),description text not null check(length(trim(description)) between 1 and 3000),reason text not null check(length(trim(reason)) between 3 and 3000),area text not null default '' check(length(area)<=200),original_item_id uuid,original_amount text not null default '0',new_amount text not null default '0',net_adjustment text not null,new_snapshot jsonb,sort_order integer not null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(change_order_id,sort_order),foreign key(organization_id,contract_id,change_order_id) references public.change_orders(organization_id,contract_id,id),foreign key(organization_id,original_item_id) references public.quotation_items(organization_id,id));
create unique index change_once_per_document on public.change_order_items(change_order_id,original_item_id) where original_item_id is not null;
create table private.finance_sequences(organization_id uuid not null references public.organizations(id),kind text not null,year integer not null,last_number bigint not null,primary key(organization_id,kind,year));
revoke all on private.finance_sequences from public,anon,authenticated;
create function private.finance_number(org uuid,kind text,prefix text) returns text language plpgsql security definer set search_path='' as $$declare yr integer;n bigint;begin
 select extract(year from now() at time zone default_timezone) into yr from public.organizations where id=org;
 insert into private.finance_sequences values(org,kind,yr,1) on conflict on constraint finance_sequences_pkey do update set last_number=private.finance_sequences.last_number+1 returning last_number into n;
 return prefix||'-'||yr||'-'||lpad(n::text,greatest(6,length(n::text)),'0');
end$$;
do $$declare t text;p text;begin
 foreach t in array array['organization_billing_settings','payment_methods','tax_codes','contracts','payment_schedules','payment_schedule_items','payment_requests','invoices','invoice_items','payments','payment_allocations','receipts','change_orders','change_order_items'] loop
 p=case t when 'organization_billing_settings' then 'billing.manage' when 'payment_methods' then 'payment.view' when 'tax_codes' then 'invoice.view' when 'contracts' then 'contract.view' when 'payment_schedules' then 'payment_schedule.view' when 'payment_schedule_items' then 'payment_schedule.view' when 'payment_requests' then 'payment_request.view' when 'invoices' then 'invoice.view' when 'invoice_items' then 'invoice.view' when 'payments' then 'payment.view' when 'payment_allocations' then 'payment.view' when 'receipts' then 'receipt.view' else 'change_order.view' end;
 execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);
 execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);
 execute format('create policy finance_read on public.%I for select to authenticated using(private.finance_access(organization_id,%L))',t,p);
 execute format('create trigger touch_updated_at before update on public.%I for each row execute function private.touch_updated_at()',t);
 execute format('create index on public.%I(organization_id,created_at desc,id)',t);
 end loop;
end$$;
insert into public.permissions(id,key,scope,description) select private.seed_uuid('business-os:'||k),k,'organization',replace(k,'.',' ') from unnest(array['contract.view','contract.create','contract.manage','payment_schedule.view','payment_schedule.manage','payment_request.view','payment_request.create','payment_request.manage','invoice.view','invoice.create','invoice.issue','invoice.manage','payment.allocate','payment.void','receipt.view','change_order.view','change_order.create','change_order.issue','change_order.manage','change_order.approve','change_order.manual','financial_report.view']) k on conflict(key) do nothing;
insert into private.role_template_permissions(role_key,permission_key)
 select r.key,p.key from private.role_templates r cross join public.permissions p where
 (p.key like 'contract.%' or p.key like 'payment_schedule.%' or p.key like 'payment_request.%' or p.key like 'invoice.%' or p.key like 'payment.%' or p.key='receipt.view' or p.key like 'change_order.%' or p.key='financial_report.view') and
 (r.key in ('owner','admin') or (r.key='accountant' and (p.key not like 'change_order.%' and p.key not in ('contract.create','contract.manage'))) or (r.key='project_manager' and p.key in ('contract.view','payment_schedule.view','change_order.view'))) on conflict do nothing;
insert into public.role_permissions(organization_id,role_id,permission_id) select r.organization_id,r.id,p.id from public.roles r join private.role_template_permissions t on t.role_key=r.key join public.permissions p on p.key=t.permission_key where p.key like 'contract.%' or p.key like 'payment_schedule.%' or p.key like 'payment_request.%' or p.key like 'invoice.%' or p.key in ('payment.allocate','payment.void','receipt.view','financial_report.view') or p.key like 'change_order.%' on conflict do nothing;
revoke all on function private.finance_access(uuid,text),private.finance_require(uuid,text),private.finance_decimal(text,boolean),private.finance_number(uuid,text,text) from public,anon,authenticated;
grant execute on function private.finance_access(uuid,text) to authenticated;
commit;
