begin;
-- An older approved requisition cannot authorize newly issuing removed/reduced scope.
create function private.execution_check_current_demand() returns trigger language plpgsql security definer set search_path='' as $$
declare revision public.execution_estimate_revisions;item public.purchase_order_items;source record;allowed_quantity numeric;committed_quantity numeric;allocation numeric;begin
 if new.status<>'issued' or old.status<>'draft' then return new;end if;
 select r.* into revision from public.execution_estimates e join public.execution_estimate_revisions r on r.id=e.current_approved_revision_id where e.contract_id=new.contract_id;
 if revision.id is null or revision.status<>'approved' or revision.scope_fingerprint<>md5(private.execution_scope(new.contract_id)::text) then raise exception 'Current approved scope and estimate required before purchase issue' using errcode='40001';end if;
 for item in select * from public.purchase_order_items where po_id=new.id loop
 for source in select ps.quantity::numeric allocated,pri.quantity::numeric requisition_quantity,l.variant_id,l.cost_kind,l.purchase_unit,l.description,s.source_type,s.source_id from public.purchase_requisition_sources ps join public.purchase_requisition_items pri on pri.id=ps.item_id join public.execution_estimate_lines l on l.id=ps.estimate_line_id join public.execution_estimate_scope_items s on s.id=l.scope_id where ps.item_id=item.requisition_item_id loop
 select coalesce(sum(l.planned_purchase_quantity::numeric),0) into allowed_quantity from public.execution_estimate_lines l join public.execution_estimate_scope_items s on s.id=l.scope_id where l.revision_id=revision.id and s.coverage='estimated' and s.source_type=source.source_type and s.source_id=source.source_id and l.variant_id is not distinct from source.variant_id and l.cost_kind=source.cost_kind and l.purchase_unit=source.purchase_unit and (source.variant_id is not null or l.description=source.description);
 select coalesce(sum(pi.quantity::numeric*ps.quantity::numeric/pri.quantity::numeric),0) into committed_quantity from public.purchase_order_items pi join public.purchase_orders po on po.id=pi.po_id join public.purchase_requisition_items pri on pri.id=pi.requisition_item_id join public.purchase_requisition_sources ps on ps.item_id=pri.id join public.execution_estimate_lines l on l.id=ps.estimate_line_id join public.execution_estimate_scope_items s on s.id=l.scope_id where po.contract_id=new.contract_id and po.status in ('issued','partially_received','received','closed') and s.source_type=source.source_type and s.source_id=source.source_id and l.variant_id is not distinct from source.variant_id and l.cost_kind=source.cost_kind and l.purchase_unit=source.purchase_unit and (source.variant_id is not null or l.description=source.description);
 select coalesce(sum(pi.quantity::numeric*ps.quantity::numeric/pri.quantity::numeric),0) into allocation from public.purchase_order_items pi join public.purchase_requisition_items pri on pri.id=pi.requisition_item_id join public.purchase_requisition_sources ps on ps.item_id=pri.id join public.execution_estimate_lines l on l.id=ps.estimate_line_id join public.execution_estimate_scope_items s on s.id=l.scope_id where pi.po_id=new.id and s.source_type=source.source_type and s.source_id=source.source_id and l.variant_id is not distinct from source.variant_id and l.cost_kind=source.cost_kind and l.purchase_unit=source.purchase_unit and (source.variant_id is not null or l.description=source.description);
 if committed_quantity+allocation>allowed_quantity then raise exception 'Award exceeds remaining current approved scope demand' using errcode='22023';end if;end loop;end loop;
 return new;
end$$;
create trigger execution_current_demand before update on public.purchase_orders for each row execute function private.execution_check_current_demand();
revoke all on function private.execution_check_current_demand() from public,anon,authenticated;
commit;

