begin;
create or replace function public.execution_search(p_organization_id uuid,p_entity text,p_filter jsonb default '{}',p_page integer default 1) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare permission text;rows jsonb;total bigint;begin
 permission=private.execution_read_permission(p_entity);
 if permission is null or not private.execution_access(p_organization_id,permission) then raise exception 'Unavailable execution records' using errcode='42501';end if;
 if p_page is null or p_page not between 1 and 10000 or jsonb_typeof(p_filter) is distinct from 'object' or octet_length(p_filter::text)>2000 or p_filter-array['category_id','estimate_id','receipt_id','project_id','contract_id','revision_id','scope_id','material_id','variant_id','vendor_id','recipe_id','requisition_id','rfq_id','quote_id','po_id','status','query']<>'{}'::jsonb then raise exception 'Invalid execution search' using errcode='22023';end if;
 execute format('select count(*) from public.%I t where t.organization_id=$1 and not exists(select 1 from jsonb_each_text($2-''query'') f where to_jsonb(t)->>f.key is distinct from f.value) and ($2->>''query'' is null or concat_ws('' '',to_jsonb(t)->>''name'',to_jsonb(t)->>''code'',to_jsonb(t)->>''description'',to_jsonb(t)->>''estimate_number'',to_jsonb(t)->>''requisition_number'',to_jsonb(t)->>''rfq_number'',to_jsonb(t)->>''po_number'',to_jsonb(t)->>''receipt_number'',to_jsonb(t)->>''reference'') ilike ''%%''||replace(replace(replace($2->>''query'',''\'',''\\''),''%%'',''\%%''),''_'',''\_'')||''%%'')',p_entity) into total using p_organization_id,p_filter;
 execute format('select coalesce(jsonb_agg(row),''[]'') from (select to_jsonb(t) row from public.%I t where t.organization_id=$1 and not exists(select 1 from jsonb_each_text($2-''query'') f where to_jsonb(t)->>f.key is distinct from f.value) and ($2->>''query'' is null or concat_ws('' '',to_jsonb(t)->>''name'',to_jsonb(t)->>''code'',to_jsonb(t)->>''description'',to_jsonb(t)->>''estimate_number'',to_jsonb(t)->>''requisition_number'',to_jsonb(t)->>''rfq_number'',to_jsonb(t)->>''po_number'',to_jsonb(t)->>''receipt_number'',to_jsonb(t)->>''reference'') ilike ''%%''||replace(replace(replace($2->>''query'',''\'',''\\''),''%%'',''\%%''),''_'',''\_'')||''%%'') order by t.created_at desc,t.id limit 25 offset $3)x',p_entity) into rows using p_organization_id,p_filter,(p_page-1)*25;
 return jsonb_build_object('rows',rows,'total',total,'page',p_page,'page_size',25);
end$$;
commit;
