begin;
create function public.brochure_read(p_organization_id uuid,p_brochure_id uuid default null,p_version_id uuid default null,p_page integer default 1) returns jsonb language plpgsql stable security definer set search_path='' as $$declare b public.brochures;v public.brochure_versions;begin
 if not private.brochure_access(p_organization_id,'brochure.view') or p_page not between 1 and 10000 then raise exception 'Unavailable brochures' using errcode='42501';end if;
 if p_brochure_id is null then return jsonb_build_object('items',(select coalesce(jsonb_agg(x),'[]') from(select id,name,slug,type,status,version,published_version_id,updated_at from public.brochures where organization_id=p_organization_id order by updated_at desc,id limit 25 offset (p_page-1)*25)x),'limits',private.brochure_config(p_organization_id),'business',(select jsonb_build_object('name',name,'slug',slug) from public.organizations where id=p_organization_id),'kit',(select jsonb_build_object('version',version,'content',content) from public.marketing_kits where organization_id=p_organization_id));end if;
 select * into b from public.brochures where organization_id=p_organization_id and id=p_brochure_id;if b.id is null then raise exception 'Unavailable brochure' using errcode='42501';end if;
 if p_version_id is not null then select * into v from public.brochure_versions where organization_id=p_organization_id and brochure_id=b.id and id=p_version_id;if v.id is null then raise exception 'Unavailable version' using errcode='42501';end if;end if;
 return jsonb_build_object('id',b.id,'name',b.name,'slug',b.slug,'status',b.status,'version',b.version,'document',case when v.id is null then b.document else v.snapshot end,'businessName',coalesce(v.business_name,(select name from public.organizations where id=p_organization_id)),'publishedVersionId',b.published_version_id,'selectedVersion',v.sequence,'limits',private.brochure_config(p_organization_id),'versions',(select coalesce(jsonb_agg(x),'[]') from(select id,sequence,summary,created_at,restored_from from public.brochure_versions where brochure_id=b.id order by sequence desc limit 25 offset (p_page-1)*25)x));
end$$;
create function public.brochure_write(p_organization_id uuid,p_brochure_id uuid,p_version integer,p_proof text,p_signature text) returns jsonb language plpgsql security definer set search_path='' as $$declare b public.brochures;proof jsonb;doc jsonb;target uuid;config jsonb;begin
 perform private.brochure_require(p_organization_id,'brochure.manage');proof=private.website_proof(p_proof,p_signature);doc=proof->'document';config=private.brochure_config(p_organization_id);
 if proof->>'purpose' is distinct from 'brochure.save' or proof->>'organizationId' is distinct from p_organization_id::text or proof->>'brochureId' is distinct from p_brochure_id::text or (proof->>'version')::integer is distinct from p_version then raise exception 'Invalid document proof' using errcode='42501';end if;
 perform private.brochure_check_document(p_organization_id,doc);
 if p_brochure_id is null then
  if (select count(*) from public.brochures where organization_id=p_organization_id and status<>'archived')>=least(200,(config->>'count')::integer) then raise exception 'Brochure count limit reached' using errcode='23514';end if;
  if proof->>'template'<>'' and not (config->>'templates')::boolean then raise exception 'Templates capability required' using errcode='42501';end if;
  insert into public.brochures(organization_id,name,slug,type,document) values(p_organization_id,doc->>'title',proof->>'slug',doc->>'type',doc) returning id into target;
  perform private.brochure_event(p_organization_id,target,'brochure.created');return jsonb_build_object('id',target,'version',1);
 end if;
 select * into b from public.brochures where organization_id=p_organization_id and id=p_brochure_id for update;
 if b.id is null or b.status in ('archived','suspended') then raise exception 'Unavailable brochure' using errcode='42501';end if;if b.version is distinct from p_version then raise exception 'Draft changed; reload' using errcode='40001';end if;
 if b.document->'form' is distinct from doc->'form' then perform private.brochure_require(p_organization_id,'brochure.forms.manage');end if;
 if b.document->'settings' is distinct from doc->'settings' then perform private.brochure_require(p_organization_id,'brochure.share');end if;
 if not (config->>'custom_design')::boolean and (b.document->'pages' is distinct from doc->'pages' or b.document->'theme' is distinct from doc->'theme') then raise exception 'Custom design capability required' using errcode='42501';end if;
 update public.brochures set document=doc,name=doc->>'title',type=doc->>'type',version=version+1 where id=b.id;
 perform private.brochure_event(p_organization_id,b.id,'brochure.updated',jsonb_build_object('version',b.version+1));return jsonb_build_object('id',b.id,'version',b.version+1);
end$$;
create function public.brochure_publish(p_organization_id uuid,p_brochure_id uuid,p_version integer,p_proof text,p_signature text,p_pdf text,p_summary text,p_restore_id uuid default null) returns uuid language plpgsql security definer set search_path='' as $$declare b public.brochures;old public.brochure_versions;proof jsonb;doc jsonb;pdf bytea;target uuid;seq integer;begin
 perform private.brochure_require(p_organization_id,'brochure.publish');perform private.brochure_require(p_organization_id,'brochure.export');
 select * into b from public.brochures where organization_id=p_organization_id and id=p_brochure_id for update;if b.id is null or b.status in ('archived','suspended') then raise exception 'Unavailable brochure' using errcode='42501';end if;if b.version is distinct from p_version then raise exception 'Stale publication' using errcode='40001';end if;
 proof=private.website_proof(p_proof,p_signature);
 if proof->>'purpose' is distinct from 'brochure.publish' or proof->>'organizationId' is distinct from p_organization_id::text or proof->>'brochureId' is distinct from b.id::text or (proof->>'version')::integer is distinct from p_version or proof->>'restoreId' is distinct from p_restore_id::text or proof->>'draftDigest' is distinct from encode(extensions.digest(convert_to(b.document::text,'UTF8'),'sha256'),'hex') then raise exception 'Invalid publication proof' using errcode='42501';end if;
 doc=proof->'document';perform private.brochure_check_document(p_organization_id,doc);
 if p_restore_id is not null then perform private.brochure_require(p_organization_id,'brochure.restore');select * into old from public.brochure_versions where organization_id=p_organization_id and brochure_id=b.id and id=p_restore_id;if old.id is null or old.snapshot is distinct from doc then raise exception 'Restore must preserve history' using errcode='42501';end if;select data into pdf from private.brochure_pdfs where version_id=old.id;
 else if length(p_pdf)>34000000 then raise exception 'PDF too large' using errcode='22023';end if;pdf=decode(p_pdf,'base64');end if;
 if pdf is null or substring(pdf from 1 for 5)<>convert_to('%PDF-','UTF8') or encode(extensions.digest(pdf,'sha256'),'hex') is distinct from proof->>'pdfDigest' then raise exception 'Invalid PDF proof' using errcode='42501';end if;
 if doc->'settings'->>'sharing'='true' then perform private.brochure_require(p_organization_id,'brochure.share');if not (private.brochure_config(p_organization_id)->>'public_share')::boolean then raise exception 'Public sharing disabled' using errcode='42501';end if;end if;
 if doc->'form'->>'enabled'='true' then perform private.brochure_require(p_organization_id,'brochure.forms.manage');if not private.entitled(p_organization_id,'crm') or not exists(select 1 from public.crm_pipeline_stages where organization_id=p_organization_id and active and outcome='open') then raise exception 'CRM and an open stage required' using errcode='42501';end if;insert into public.lead_sources(organization_id,key,name) values(p_organization_id,'brochure','Brochure') on conflict(organization_id,key) do nothing;end if;
 select coalesce(max(sequence),0)+1 into seq from public.brochure_versions where brochure_id=b.id;
 insert into public.brochure_versions(organization_id,brochure_id,sequence,snapshot,business_name,summary,pdf_digest,restored_from) values(p_organization_id,b.id,seq,doc,coalesce(old.business_name,proof->>'businessName'),p_summary,proof->>'pdfDigest',p_restore_id) returning id into target;
 insert into private.brochure_pdfs(version_id,data) values(target,pdf);
 update public.brochures set published_version_id=target,status='published',version=version+1 where id=b.id;
 perform private.brochure_event(p_organization_id,b.id,case when p_restore_id is null then 'brochure.published' else 'brochure.version_restored' end,jsonb_build_object('sequence',seq));return target;
end$$;
create function public.brochure_status(p_organization_id uuid,p_brochure_id uuid,p_version integer,p_status text) returns void language plpgsql security definer set search_path='' as $$declare b public.brochures;begin
 perform private.brochure_require(p_organization_id,case when p_status='unpublished' then 'brochure.publish' else 'brochure.manage' end);select * into b from public.brochures where organization_id=p_organization_id and id=p_brochure_id for update;if b.id is null or b.version is distinct from p_version or b.status='suspended' or p_status not in ('unpublished','archived','draft') or p_status='draft' and b.status<>'archived' then raise exception 'Unavailable status transition' using errcode='42501';end if;
 update public.brochures set status=p_status,version=version+1 where id=b.id;perform private.brochure_event(p_organization_id,b.id,'brochure.'||p_status);
end$$;
create function public.brochure_document_digest(p_organization_id uuid,p_brochure_id uuid) returns text language plpgsql stable security definer set search_path='' as $$begin if not private.brochure_access(p_organization_id,'brochure.publish') then raise exception 'Unavailable document' using errcode='42501';end if;return(select encode(extensions.digest(convert_to(document::text,'UTF8'),'sha256'),'hex') from public.brochures where organization_id=p_organization_id and id=p_brochure_id);end$$;
create function public.brochure_pdf_read(p_organization_id uuid,p_brochure_id uuid,p_version_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare v public.brochure_versions;begin perform private.brochure_require(p_organization_id,'brochure.export');select * into v from public.brochure_versions where organization_id=p_organization_id and brochure_id=p_brochure_id and id=p_version_id;if v.id is null then raise exception 'Unavailable PDF' using errcode='42501';end if;perform private.brochure_event(p_organization_id,p_brochure_id,'brochure.exported',jsonb_build_object('sequence',v.sequence));return jsonb_build_object('data',(select encode(data,'base64') from private.brochure_pdfs where version_id=v.id),'digest',v.pdf_digest);end$$;
do $$declare f record;begin for f in select oid::regprocedure signature from pg_proc where pronamespace='public'::regnamespace and proname in ('brochure_read','brochure_write','brochure_publish','brochure_status','brochure_document_digest','brochure_pdf_read') loop execute format('revoke all on function %s from public,anon',f.signature);execute format('grant execute on function %s to authenticated',f.signature);end loop;end$$;
commit;
