begin;
create table public.brochures(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),name text not null check(length(trim(name)) between 1 and 160),slug text not null check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and length(slug) between 1 and 80),type text not null check(length(type) between 1 and 100),status text not null default 'draft' check(status in ('draft','published','unpublished','archived','suspended')),version integer not null default 1 check(version>0),document jsonb not null check(jsonb_typeof(document)='object' and octet_length(document::text)<=2500000),published_version_id uuid,created_by uuid references public.profiles(id) default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,slug)
);
create table public.brochure_versions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),brochure_id uuid not null,sequence integer not null check(sequence>0),snapshot jsonb not null check(jsonb_typeof(snapshot)='object' and octet_length(snapshot::text)<=2500000),business_name text not null,summary text not null default '' check(length(summary)<=500),pdf_digest text not null check(pdf_digest ~ '^[a-f0-9]{64}$'),restored_from uuid,created_by uuid references public.profiles(id) default auth.uid(),created_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,brochure_id,id),unique(brochure_id,sequence),foreign key(organization_id,brochure_id) references public.brochures(organization_id,id),foreign key(organization_id,brochure_id,restored_from) references public.brochure_versions(organization_id,brochure_id,id)
);
alter table public.brochures add foreign key(organization_id,id,published_version_id) references public.brochure_versions(organization_id,brochure_id,id);
create table public.marketing_kits(organization_id uuid primary key references public.organizations(id),version integer not null default 1,content jsonb not null default '{"brand":{},"content":[],"blocks":[],"types":["Company Profile","Services","Project Portfolio","Materials & Finishes"]}' check(jsonb_typeof(content)='object' and octet_length(content::text)<=2500000),updated_at timestamptz not null default now());
create table public.brochure_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),brochure_id uuid,actor_id uuid references public.profiles(id) default auth.uid(),action text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now(),foreign key(organization_id,brochure_id) references public.brochures(organization_id,id));
create table public.brochure_plan_limits(plan_id uuid primary key references public.plans(id),configuration jsonb not null default '{}' check(jsonb_typeof(configuration)='object' and octet_length(configuration::text)<=4000));
create table private.brochure_pdfs(version_id uuid primary key references public.brochure_versions(id),data bytea not null check(octet_length(data) between 100 and 25000000));
create table private.brochure_metrics(brochure_id uuid not null references public.brochures(id),day date not null,kind text not null check(kind in ('view','download','cta','lead')),hits bigint not null default 0,primary key(brochure_id,day,kind));
create table private.brochure_form_limits(brochure_id uuid not null references public.brochures(id),bucket timestamptz not null,hits integer not null,primary key(brochure_id,bucket));
create function private.brochure_access(org uuid,permission text) returns boolean language sql stable security definer set search_path='' as $$select private.has_permission(org,permission) and private.entitled(org,'brochure');$$;
create function private.brochure_require(org uuid,permission text) returns void language plpgsql security definer set search_path='' as $$begin perform 1 from public.organizations where id=org for update;if not private.brochure_access(org,permission) then raise exception 'Unavailable brochure operation' using errcode='42501';end if;end$$;
create function private.brochure_config(org uuid) returns jsonb language sql stable security definer set search_path='' as $$select '{"count":20,"pages":50,"storage_bytes":104857600,"templates":true,"custom_design":true,"public_share":true,"analytics":false}'::jsonb||coalesce((select l.configuration from public.organizations o join public.brochure_plan_limits l on l.plan_id=o.plan_id where o.id=org),'{}')||coalesce((select e.configuration from public.organization_entitlements e join public.modules m on m.id=e.module_id where e.organization_id=org and m.key='brochure' and e.enabled and e.valid_from<=now() and (e.valid_until is null or e.valid_until>now()) order by case e.source when 'manual' then 0 when 'addon' then 1 else 2 end,e.updated_at desc limit 1),'{}');$$;
create function private.brochure_event(org uuid,item uuid,event text,details jsonb default '{}') returns void language plpgsql security definer set search_path='' as $$begin insert into public.brochure_events(organization_id,brochure_id,action,metadata) values(org,item,event,details);insert into public.audit_logs(actor_user_id,organization_id,action,entity_type,entity_id) values(auth.uid(),org,event,'brochures',coalesce(item::text,org::text));end$$;
create function private.brochure_assets(doc jsonb) returns setof uuid language sql immutable set search_path='' as $$select distinct value::uuid from (select doc->'settings'->>'cover' value union all select c->>'asset' from jsonb_array_elements(doc->'pages') p cross join lateral jsonb_array_elements(p->'components') c union all select a#>>'{}' from jsonb_array_elements(doc->'pages') p cross join lateral jsonb_array_elements(p->'components') c cross join lateral jsonb_array_elements(coalesce(c->'assets','[]')) a) x where value is not null;$$;
create function private.brochure_check_document(org uuid,doc jsonb) returns void language plpgsql stable security definer set search_path='' as $$declare aid uuid;begin
 if doc->>'schemaVersion' is distinct from '1' or jsonb_typeof(doc->'pages') is distinct from 'array' or coalesce(jsonb_array_length(doc->'pages'),0) not between 1 and least(100,(private.brochure_config(org)->>'pages')::integer) then raise exception 'Invalid page count' using errcode='22023';end if;
 for aid in select private.brochure_assets(doc) loop if not exists(select 1 from public.website_assets where organization_id=org and id=aid and status='ready' and mime='image/webp') then raise exception 'Unavailable image' using errcode='42501';end if;end loop;
end$$;
do $$declare t text;begin foreach t in array array['brochures','brochure_versions','marketing_kits','brochure_events'] loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);execute format('create policy brochure_read on public.%I for select to authenticated using(private.brochure_access(organization_id,''brochure.view''))',t);end loop;end$$;
revoke select on public.brochures,public.brochure_versions,public.marketing_kits from authenticated;
grant select(id,organization_id,name,slug,type,status,version,published_version_id,created_by,created_at,updated_at) on public.brochures to authenticated;
grant select(id,organization_id,brochure_id,sequence,summary,restored_from,created_by,created_at) on public.brochure_versions to authenticated;
create trigger brochure_touch before update on public.brochures for each row execute function private.touch_updated_at();
create trigger brochure_immutable before update or delete on public.brochure_versions for each row execute function private.ops_immutable();
create trigger brochure_pdf_immutable before update or delete on private.brochure_pdfs for each row execute function private.ops_immutable();
create trigger brochure_event_immutable before update or delete on public.brochure_events for each row execute function private.ops_immutable();
create index brochures_list on public.brochures(organization_id,updated_at desc,id);
create index brochure_versions_list on public.brochure_versions(organization_id,brochure_id,sequence desc);
alter table public.brochure_plan_limits enable row level security;alter table public.brochure_plan_limits force row level security;revoke all on public.brochure_plan_limits from public,anon,authenticated;grant select on public.brochure_plan_limits to authenticated;create policy platform_brochure_read on public.brochure_plan_limits for select to authenticated using(private.has_platform_permission('platform.catalog.view'));
do $$declare k text;r text;begin foreach k in array array['brochure.view','brochure.manage','brochure.publish','brochure.restore','brochure.export','brochure.media.manage','brochure.forms.manage','brochure.brand.manage','brochure.share','brochure.analytics.view'] loop insert into public.permissions(key,scope,description) values(k,'organization',k) on conflict(key) do nothing;foreach r in array array['owner','admin'] loop insert into private.role_template_permissions(role_key,permission_key) values(r,k) on conflict do nothing;insert into public.role_permissions(organization_id,role_id,permission_id) select roles.organization_id,roles.id,p.id from public.roles roles join public.permissions p on p.key=k where roles.key=r on conflict do nothing;end loop;end loop;end$$;
revoke all on private.brochure_pdfs,private.brochure_metrics,private.brochure_form_limits from public,anon,authenticated;
revoke all on function private.brochure_require(uuid,text),private.brochure_access(uuid,text),private.brochure_config(uuid),private.brochure_event(uuid,uuid,text,jsonb),private.brochure_assets(jsonb),private.brochure_check_document(uuid,jsonb) from public,anon,authenticated;
grant execute on function private.brochure_access(uuid,text) to authenticated;
commit;
