packages:
  - apps/*
  - packages/*

overrides:
  source-map-js: 1.2.2

onlyBuiltDependencies:
  - esbuild
  - sharp
  - '@tailwindcss/oxide'
patchedDependencies:
  braces@3.0.3: patches/braces@3.0.3.patch
