/** Version 1 report layout. All values are escaped, including keys and filters. */
export function reportHtml(
  report: {
    kind: string;
    organization_name?: string | undefined;
    generated_at: string;
    generated_by?: string | undefined;
    basis?: string | undefined;
    filters: Record<string, unknown>;
    rows: Record<string, unknown>[];
    summary?: Record<string, unknown>[] | undefined;
    aging?: Record<string, unknown>[] | undefined;
    commercial?: Record<string, unknown> | undefined;
  },
  snapshotId: string,
) {
  const escape = (value: unknown) =>
    String(value ?? '')
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
  const value = (item: unknown) =>
    typeof item === 'object' && item !== null
      ? JSON.stringify(item)
      : String(item ?? '');
  const table = (rows: Record<string, unknown>[]) => {
    const keys = [...new Set(rows.flatMap((row) => Object.keys(row)))].filter(
      (key) =>
        !key.endsWith('_id') &&
        key !== 'id' &&
        rows.some(
          (row) =>
            row[key] !== null && row[key] !== undefined && row[key] !== '',
        ),
    );
    // Narrow groups preserve legibility for reports with many dimensions.
    const groups: string[][] = [];
    for (let index = 0; index < keys.length; index += 5)
      groups.push(keys.slice(index, index + 5));
    return rows.length
      ? groups
          .map(
            (columns, index) =>
              `<h3>${index ? 'Additional dimensions' : 'Records'}</h3><table><thead><tr><th>#</th>${columns.map((key) => `<th>${escape(key.replaceAll('_', ' '))}</th>`).join('')}</tr></thead><tbody>${rows.map((row, rowIndex) => `<tr><td>${rowIndex + 1}</td>${columns.map((key) => `<td>${escape(value(row[key]))}</td>`).join('')}</tr>`).join('')}</tbody></table>`,
          )
          .join('')
      : '<p>No records match these filters.</p>';
  };
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${escape(report.kind)} report</title><style>@page{size:A4 landscape;margin:16mm 14mm 20mm}*{box-sizing:border-box}body{font:10px/1.5 Arial,sans-serif;color:#203044}header{border-bottom:3px solid #147d80;padding-bottom:12px}h1{font-size:26px;margin:4px 0;text-transform:capitalize}h2{font-size:16px;margin-top:24px}h3{font-size:11px;color:#506575;margin:14px 0 6px}p{overflow-wrap:anywhere}.eyebrow{font-size:10px;letter-spacing:2px;text-transform:uppercase;color:#147d80}.meta{color:#506575}.basis{background:#edf6f5;padding:12px;border-left:3px solid #147d80}table{border-collapse:collapse;width:100%;table-layout:fixed;margin:8px 0 18px}thead{display:table-header-group}th{background:#203044;color:white;text-align:left;text-transform:capitalize}th,td{padding:7px;border-bottom:1px solid #dce4e8;overflow-wrap:anywhere;vertical-align:top}th:first-child,td:first-child{width:30px}tr{break-inside:avoid}tbody tr:nth-child(even){background:#f5f8fa}h2,h3{break-after:avoid}</style></head><body><header><div class="eyebrow">Business OS · Internal report</div><h1>${escape(report.kind)} report</h1><strong>${escape(report.organization_name ?? '')}</strong><p class="meta">Generated ${escape(report.generated_at)} · Snapshot ${escape(snapshotId)}<br>Generated by ${escape(report.generated_by ?? '')} · Renderer 1</p></header><p class="basis">${escape(report.basis ?? 'Cumulative canonical project balances at generation time.')}</p><p><strong>Filters:</strong> ${escape(JSON.stringify(report.filters))}</p>${report.summary?.length ? '<h2>Summary by source, status and currency</h2>' + table(report.summary) : ''}${report.aging?.length ? '<h2>Receivables aging</h2>' + table(report.aging) : ''}${report.commercial ? '<h2>Commercial basis</h2>' + table([report.commercial]) : ''}<h2>Detailed records</h2>${table(report.rows)}</body></html>`;
}
