import { PDFDocument } from 'pdf-lib';

export interface PdfOptions {
  brochure?: boolean;
  title?: string;
  author?: string;
  subject?: string;
}
export type PdfProvider = 'node' | 'cloudflare-rest';

export class PdfServiceError extends Error {
  readonly code: string;
  readonly status = 503;

  constructor(code: string) {
    super(code);
    this.name = 'PdfServiceError';
    this.code = code;
  }
}

const MAX_HTML_BYTES = 80_000_000;
const MAX_EMBEDDED_BYTES = 50_000_000;
const MAX_PDF_BYTES = 25_000_000;
const RENDER_TIMEOUT_MS = 30_000;
let active = 0;

// The documents are generated by allowlisted, escaped server-side renderers.
// Defense in depth: reject active content and all fetchable resources.
export function validatePrintHtml(html: string): string {
  if (!html || Buffer.byteLength(html, 'utf8') > MAX_HTML_BYTES)
    throw new Error('PDF input exceeds rendering limit');
  if (
    /<\s*(?:script|iframe|object|embed|base|link|svg|video|audio)\b/i.test(html)
  )
    throw new Error('PDF contains forbidden active or remote content');
  if (
    /@import\b|url\(\s*['"]?(?!data:image\/(?:png|jpeg|webp);base64,)/i.test(
      html,
    )
  )
    throw new Error('PDF styles cannot load external resources');
  if (/\b(?:srcset|poster)\s*=/i.test(html))
    throw new Error('PDF cannot load external resources');
  const sources = [...html.matchAll(/\bsrc\s*=\s*["']([^"']*)["']/gi)];
  let embeddedSize = 0;
  for (const [, source] of sources) {
    if (
      !/^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/i.test(
        source ?? '',
      )
    )
      throw new Error('PDF image must be a bounded embedded raster image');
    embeddedSize += Math.floor(((source ?? '').length * 3) / 4);
    if (embeddedSize > MAX_EMBEDDED_BYTES)
      throw new Error('PDF images exceed rendering limit');
  }
  for (const [, url] of html.matchAll(/\bhref\s*=\s*["']([^"']*)["']/gi)) {
    if (!/^(?:https?:\/\/|mailto:|tel:|#)/i.test(url ?? ''))
      throw new Error('PDF link uses a forbidden protocol');
  }
  const csp =
    "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; img-src data:; style-src 'unsafe-inline'; font-src data:; script-src 'none'; connect-src 'none'; object-src 'none'; frame-src 'none'; base-uri 'none'; form-action 'none'\">";
  if (/<head\b[^>]*>/i.test(html))
    return html.replace(/<head\b[^>]*>/i, (match) => match + csp);
  return (
    '<!doctype html><html><head>' +
    csp +
    '</head><body>' +
    html +
    '</body></html>'
  );
}

export function configuredPdfProvider(
  env: Record<string, string | undefined> = process.env,
): PdfProvider {
  const value = env.PDF_RENDERER;
  const isWorker =
    typeof navigator !== 'undefined' &&
    navigator.userAgent === 'Cloudflare-Workers';
  if (value === 'cloudflare-rest') return 'cloudflare-rest';
  if (value === 'node' && !isWorker) return 'node';
  if (!value && !isWorker) return 'node';
  throw new PdfServiceError('PDF_RENDERER_UNAVAILABLE');
}

export function cloudflarePdfRequest(
  html: string,
  _options: PdfOptions,
  env: Record<string, string | undefined> = process.env,
) {
  const accountId = env.CF_BROWSER_ACCOUNT_ID;
  const token = env.CF_BROWSER_API_TOKEN;
  if (!accountId || !/^[a-f0-9]{32}$/i.test(accountId) || !token)
    throw new PdfServiceError('PDF_RENDERER_UNAVAILABLE');
  return {
    url: `https://api.cloudflare.com/client/v4/accounts/${accountId}/browser-rendering/pdf`,
    token,
    body: {
      html,
      setJavaScriptEnabled: false,
      rejectRequestPattern: ['^https?://', '^file://', '^ftp://', '^wss?://'],
      rejectResourceTypes: [
        'script',
        'xhr',
        'fetch',
        'websocket',
        'eventsource',
      ],
      pdfOptions: {
        format: 'a4',
        preferCSSPageSize: true,
        printBackground: true,
        displayHeaderFooter: false,
        timeout: RENDER_TIMEOUT_MS,
      },
      actionTimeout: RENDER_TIMEOUT_MS,
    },
  };
}

async function cloudflarePdf(html: string, options: PdfOptions) {
  const request = cloudflarePdfRequest(html, options);
  const response = await fetch(request.url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${request.token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(request.body),
    signal: AbortSignal.timeout(RENDER_TIMEOUT_MS),
    redirect: 'error',
  });
  // Do not return a provider error body; it could contain private input.
  if (
    !response.ok ||
    !response.headers.get('content-type')?.includes('application/pdf')
  )
    throw new PdfServiceError('PDF_RENDER_FAILED');
  return Buffer.from(await response.arrayBuffer());
}

async function applyMetadata(bytes: Uint8Array, options: PdfOptions) {
  if (!options.title && !options.author && !options.subject)
    return Buffer.from(bytes);
  const document = await PDFDocument.load(bytes);
  if (options.title) document.setTitle(options.title);
  if (options.author) document.setAuthor(options.author);
  if (options.subject) document.setSubject(options.subject);
  document.setCreator('Business OS');
  return Buffer.from(await document.save());
}

/**
 * Node uses isolated Chromium. Workers use only the explicitly configured
 * Cloudflare Browser Rendering REST provider. No plain-text fallback.
 * Authentication, allowed data projections and snapshot integrity remain
 * the responsibility of the existing protected route and repository.
 */
export async function renderPdf(
  html: string,
  options: PdfOptions = {},
): Promise<Buffer> {
  const provider = configuredPdfProvider();
  if (active >= 2) throw new PdfServiceError('PDF_RENDERER_BUSY');
  const safeHtml = validatePrintHtml(html);
  active++;
  try {
    const bytes =
      provider === 'node'
        ? await (await import('./pdf.node')).renderNodePdf(safeHtml, options)
        : await cloudflarePdf(safeHtml, options);
    if (
      bytes.byteLength < 5 ||
      Buffer.from(bytes).toString('ascii', 0, 5) !== '%PDF-'
    )
      throw new PdfServiceError('PDF_RENDER_FAILED');
    if (bytes.byteLength > MAX_PDF_BYTES)
      throw new PdfServiceError('PDF_RENDER_LIMIT');
    return await applyMetadata(bytes, options);
  } finally {
    active--;
  }
}
