import { assetReferences, pageSize, validateDocument, type BrochureDocument, type Component } from './model';
export const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export interface RenderOptions { assetUrl?:(id:string)=>string; print?:boolean; watermark?:string; businessName?:string }
export function componentHtml(c:Component,d:BrochureDocument,index:number,o:RenderOptions={}):string {
  const e=escapeHtml;
  const image=(id:string,alt=c.alt)=>`<img src="${e(o.assetUrl?.(id)??'')}" alt="${e(alt)}" loading="${o.print?'eager':'lazy'}" style="width:100%;height:100%;object-fit:${c.fit};object-position:${c.focalX}% ${c.focalY}%;${d.theme.imageTreatment==='grayscale'?'filter:grayscale(1);':''}"/>`;
  let body='';
  if(c.type==='page_number')body=e(index+d.numbering.start);
  else if(c.type==='divider')body=`<hr style="border:0;border-top:1px solid ${c.style.color??d.theme.border};width:100%"/>`;
  else if(c.type==='shape')body='';
  else if(['image','logo'].includes(c.type))body=c.asset?image(c.asset):`<div class="image-placeholder">${e(c.alt||'Choose an image')}</div>`;
  else if(['gallery','image_grid','room_gallery','before_after'].includes(c.type))body=`<div style="display:grid;grid-template-columns:repeat(${c.type==='before_after'?2:c.columns},minmax(0,1fr));gap:2mm;height:100%">${c.assets.map(id=>`<div style="min-height:0;overflow:hidden">${image(id)}</div>`).join('')}</div>`;
  else if(c.type==='table')body=`<table>${c.rows.map((r,i)=>`<tr>${r.map(cell=>`<${i?'td':'th'}>${e(cell)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table>`;
  else {
    const tag=c.type==='heading'?'h2':'div';
    body=`${c.asset?`<div style="height:48%;margin-bottom:3mm">${image(c.asset)}</div>`:''}<${tag} class="brochure-text">${e(c.text)}</${tag}>${c.subtitle?`<p class="brochure-subtitle">${e(c.subtitle)}</p>`:''}`;
    if(c.type==='pricing'&&!c.text)body='<span>Public price not configured</span>';
    if(c.rows.length)body+=`<ol>${c.rows.map(row=>`<li>${row.map(e).join(' - ')}</li>`).join('')}</ol>`;
  }
  if(c.link)body=`<a href="${e(c.link)}" ${c.link.startsWith('https:')?'rel="noopener noreferrer"':''}>${body}</a>`;
  return body;
}
export function componentCss(c:Component,d:BrochureDocument){const s=c.style;return `position:absolute;left:${c.x}mm;top:${c.y}mm;width:${c.width}mm;height:${c.height}mm;transform:rotate(${c.rotation}deg);font-family:'${s.font}';font-size:${s.size}pt;font-weight:${s.weight};line-height:${s.lineHeight};letter-spacing:${s.letterSpacing}pt;text-align:${s.align};color:${s.color??d.theme.text};background:${s.background??'transparent'};border:${s.borderWidth}mm solid ${s.border??d.theme.border};border-radius:${s.radius}mm;padding:${s.padding}mm;opacity:${s.opacity};text-transform:${s.transform};--paragraph-spacing:${s.paragraphSpacing}mm;`;}
export function pageHtml(d:BrochureDocument,index:number,o:RenderOptions={}):string{
  const p=d.pages[index];if(!p)return '';const [w,h]=pageSize(d);const bleed=o.print?d.bleed:0;
  return `<section class="brochure-sheet" id="page-${escapeHtml(p.id)}" aria-label="${escapeHtml(p.name)}" style="width:${w+bleed*2}mm;height:${h+bleed*2}mm;background:${p.background}"><div class="brochure-trim" style="position:relative;left:${bleed}mm;top:${bleed}mm;width:${w}mm;height:${h}mm">${p.showHeader?`<header style="position:absolute;left:${d.margin}mm;top:5mm;font:9pt '${d.theme.bodyFont}'">${escapeHtml(d.header)}</header>`:''}${p.components.filter(c=>!c.hidden).map(c=>`<div data-component="${escapeHtml(c.id)}" data-label="${escapeHtml(c.label||c.type)}" class="brochure-component" style="${componentCss(c,d)}">${componentHtml(c,d,index,o)}</div>`).join('')}${p.showFooter?`<footer style="position:absolute;left:${d.margin}mm;right:${d.margin}mm;bottom:5mm;font:8pt '${d.theme.bodyFont}'">${escapeHtml(d.footer)}</footer>`:''}${d.numbering.enabled&&(!d.numbering.hideCover||index>0)?`<span style="position:absolute;bottom:5mm;left:${d.margin}mm;right:${d.margin}mm;text-align:${d.numbering.position};font:8pt '${d.theme.bodyFont}'">${index+d.numbering.start}</span>`:''}${o.watermark||d.settings.watermark?`<div style="position:absolute;inset:40% 0;pointer-events:none;text-align:center;opacity:.18;font:40pt Arial;transform:rotate(-25deg)">${escapeHtml(o.watermark||d.settings.watermark)}</div>`:''}</div></section>`;
}
export function brochureCss(d:BrochureDocument){const [w,h]=pageSize(d);return `@page{size:${w+d.bleed*2}mm ${h+d.bleed*2}mm;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0}body{color:${d.theme.text};font-family:'${d.theme.bodyFont}';background:#e9e7e2}.brochure-sheet{position:relative;break-after:page;overflow:hidden;margin:0 auto;print-color-adjust:exact;-webkit-print-color-adjust:exact}.brochure-sheet:last-child{break-after:auto}.brochure-component{overflow:visible;overflow-wrap:anywhere}.brochure-text{margin:0;font:inherit;white-space:pre-wrap}.brochure-subtitle{margin:var(--paragraph-spacing) 0 0;white-space:pre-wrap;font-size:.8em;line-height:1.5}a{color:inherit;text-decoration:none;display:block}table{width:100%;border-collapse:collapse;table-layout:fixed;font:inherit}th,td{border:1px solid ${d.theme.border};padding:2mm;text-align:left;overflow-wrap:anywhere}th{background:${d.theme.secondary}}img{display:block}.image-placeholder{height:100%;display:flex;align-items:center;justify-content:center;background:${d.theme.secondary};color:${d.theme.muted};font:10pt Arial}ol{padding-left:6mm;margin:2mm 0}li{margin:1mm 0}@media print{body{background:white}.brochure-sheet{margin:0;box-shadow:none}}`;}
export function brochureHtml(input:unknown,o:RenderOptions={}):string{const d=validateDocument(input);return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${escapeHtml(d.title)}</title><meta name="author" content="${escapeHtml(o.businessName??'')}"><style>${brochureCss(d)}</style></head><body>${d.pages.map((_,i)=>pageHtml(d,i,o)).join('')}</body></html>`;}
export function imageWarnings(d:BrochureDocument,assets:ReadonlyArray<{id:string;width:number|null;height:number|null}>):string[]{const warnings:string[]=[];for(const p of d.pages)for(const c of p.components)for(const id of [...(c.asset?[c.asset]:[]),...c.assets]){const a=assets.find(a=>a.id===id);if(a?.width&&a.height&&Math.min(a.width/(c.width/25.4),a.height/(c.height/25.4))<150)warnings.push(`${p.name}: ${c.label||c.type} may appear low quality when printed.`);}return [...new Set(warnings)];}
export function assertAssets(d:BrochureDocument,ids:ReadonlySet<string>){for(const id of assetReferences(d))if(!ids.has(id))throw new Error('An image is missing or unavailable');}
