// Every required behavior keeps its own result; a root-page PASS cannot close it.
export const required = {
  auth: [
    'registration',
    'logout',
    'expired-session',
    'membership-suspension',
    'organization-switch',
    'role-change',
  ],
  'auth-recovery': [
    'inbox-receipt',
    'reset-link',
    'new-password',
    'old-password-denied',
    'token-reuse-denied',
    'expired-token-denied',
  ],
  rls: [
    'crm',
    'billing',
    'procurement',
    'inventory',
    'execution',
    'website',
    'brochure',
    'automation',
    'notifications',
    'reports',
    'storage',
    'pdf',
    'foreign-write',
  ],
  rbac: [
    'owner-a-allowed',
    'user-a-allowed',
    'user-a-denied',
    'owner-b-allowed',
    'user-b-allowed',
    'user-b-denied',
    'accounts-allowed',
    'accounts-denied',
    'project-manager-allowed',
    'project-manager-denied',
    'site-supervisor-allowed',
    'site-supervisor-denied',
    'store-manager-allowed',
    'store-manager-denied',
    'website-brochure-allowed',
    'website-brochure-denied',
  ],
  entitlements: ['enabled', 'disabled', 'limits', 'direct-api-denied'],
  storage: [
    'upload',
    'download',
    'private',
    'public',
    'capability',
    'expired-capability',
    'foreign-denied',
    'delete',
    'replacement',
  ],
  quotation: [
    'customer',
    'project',
    'quote',
    'revision',
    'pricing-snapshot',
    'pdf',
    'send',
    'acceptance',
    'immutable-history',
  ],
  billing: ['invoice', 'due-date', 'payment-state', 'reminder', 'balance'],
  procurement: [
    'requisition',
    'rfq',
    'vendor-quote',
    'purchase-order',
    'partial-receipt',
    'inventory-update',
    'cost-update',
    'duplicate-receipt-denied',
  ],
  inventory: [
    'receive',
    'issue',
    'consume',
    'return',
    'scrap',
    'adjustment',
    'ledger-consistency',
  ],
  execution: [
    'project',
    'milestone',
    'task',
    'inspection',
    'snag',
    'reinspection',
    'handover',
    'transitions',
  ],
  automation: [
    'event',
    'condition',
    'action',
    'notification',
    'email',
    'history',
    'retry',
    'duplicate-event',
  ],
  worker: [
    'queued',
    'process',
    'success',
    'failure',
    'retry',
    'restart',
    'recovery',
  ],
  email: [
    'auth-verification',
    'password-reset',
    'invitation',
    'quotation',
    'invoice-reminder',
    'automation',
    'provider-accepted',
    'inbox-delivered',
    'template',
    'links',
  ],
  'email-failure': [
    'business-operation',
    'failure-recorded',
    'retry',
    'duplicate-prevention',
  ],
  pdf: [
    'quotation',
    'invoice',
    'project',
    'procurement',
    'inventory',
    'execution',
    'brochure',
    'reports',
    'authorization',
    'tenant-isolation',
    'integrity',
  ],
  reports: [
    'crm',
    'sales',
    'quotation',
    'billing',
    'receivables',
    'project',
    'procurement',
    'inventory',
    'execution',
    'snag',
    'handover',
    'filters',
    'authorization',
    'totals',
    'pagination',
    'export',
    'pdf',
  ],
  website: [
    'create',
    'preview',
    'publish',
    'public',
    'lead',
    'crm',
    'rollback',
    'draft-isolation',
    'not-found',
    'headers',
  ],
  brochure: [
    'create',
    'edit',
    'preview',
    'pdf',
    'publish',
    'public',
    'thumbnail',
    'lead',
    'rollback',
    'draft-isolation',
  ],
  'dns-tls': [
    'dns',
    'tls',
    'routing',
    'ownership',
    'removal',
    'suspension',
    'foreign-hostname',
  ],
  performance: [
    'api',
    'dashboard',
    'crm',
    'quotation',
    'project',
    'reports',
    'pdf',
    'website',
    'brochure',
    'worker',
    'approved-budget',
  ],
  monitoring: [
    'http',
    'database',
    'worker',
    'email',
    'automation',
    'pdf',
    'storage',
    'auth',
  ],
  backup: ['availability', 'retention', 'pitr', 'access', 'restore-process'],
  restore: [
    'database',
    'schema',
    'rls',
    'functions',
    'triggers',
    'application',
    'auth',
  ],
  rollback: [
    'current-release',
    'previous-release',
    'smoke',
    'migration-compatibility',
  ],
  deployment: [
    'clean-checkout',
    'frozen-install',
    'build',
    'migration',
    'deployment',
    'health',
    'smoke',
  ],
  security: [
    'idor',
    'tenant-isolation',
    'rbac',
    'entitlements',
    'rate-limit',
    'file',
    'pdf',
    'storage',
    'public-private',
    'auth',
  ],
  browser: [
    'live-auth',
    'live-catalog',
    'live-crm',
    'live-quotation',
    'live-finance',
    'live-execution',
    'live-operations',
    'live-automation',
    'live-brochure',
  ],
  cleanup: ['tenant-boundary', 'resources', 'organizations', 'identities'],
};
export function missingCoverage(
  report,
  reason = 'HOSTED_PROCEDURE_NOT_EXECUTED',
) {
  if (!report.checks.some((c) => c.test === 'email.invitation'))
    report.add(
      'email.invitation',
      'NOT APPLICABLE',
      'NOT_APPLICABLE',
      'NO_EMAIL_INVITATION_FEATURE',
    );
  for (const [group, cases] of Object.entries(required))
    for (const name of cases) {
      const id = `${group}.${name}`;
      if (!report.checks.some((c) => c.test === id))
        report.add(id, 'BLOCKED', 'ENVIRONMENT_LIMITATION', reason);
    }
  // These features have no production implementation in the current monolith.
  // External bucket tests do not substitute for its database-backed media adapter.
}
