\set ON_ERROR_STOP on
begin;
create function pg_temp.automation_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end$$;
create function pg_temp.automation_denied(statement text,label text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege or check_violation or invalid_parameter_value or serialization_failure or unique_violation or foreign_key_violation then raise notice 'PASS: %',label;return;end;raise exception 'FAIL: %',label;end$$;
set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';r jsonb;config jsonb='{"name":"Database automation test","description":"","event":"lead.created","mode":"event","status":"active","conditions":[],"actions":[{"kind":"notify","recipient":"actor","title":"Review enquiry","priority":"normal","delayMinutes":0,"dueBasis":"event","template":"operational_notice","audience":"internal"}],"cooldownMinutes":60,"maxPerEntity":3,"dailyLimit":100,"scheduleHour":9}';source uuid;begin
 perform pg_temp.automation_denied(format('select public.automation_rule_save(%L,null,0,%L)',org,jsonb_set(config,'{conditions}','[{"field":"status","operator":"eq"}]')),'missing condition value rejected');
 perform pg_temp.automation_denied(format('select public.automation_rule_save(%L,null,0,%L)',org,jsonb_set(config,'{dailyLimit}','"100"')),'string daily limit rejected');
 perform pg_temp.automation_denied(format('select public.automation_rule_save(%L,null,0,%L)',org,jsonb_set(config,'{actions,0,delayMinutes}','1.5')),'fractional action delay rejected');
 perform pg_temp.automation_denied(format('select public.automation_rule_save(%L,null,0,%L)',org,config||'{"script":"select secret"}'),'arbitrary rule code rejected');
 r=public.automation_rule_save(org,null,0,config);perform set_config('test.automation_rule',r->>'id',true);
 perform pg_temp.automation_assert((r->>'version')::integer=1,'first immutable rule revision created');
 perform pg_temp.automation_denied(format('select public.automation_rule_save(%L,%L,0,%L)',org,r->>'id',config),'stale rule update rejected');
 source=public.crm_save(org,'leads',jsonb_build_object('name','Automation integration enquiry','phone','+12025550177','source_id',(select id from public.lead_sources where organization_id=org and active limit 1),'stage_id',(select id from public.crm_pipeline_stages where organization_id=org and active and outcome='open' order by sort_order limit 1)));
 perform set_config('test.automation_source',source::text,true);
 perform pg_temp.automation_assert((select count(*)=1 from public.automation_events where entity_id=source and event_type='lead.created'),'canonical CRM mutation atomically captures one event');
 perform set_config('test.automation_event',(select id::text from public.automation_events where entity_id=source and event_type='lead.created'),true);
 perform pg_temp.automation_denied(format('insert into public.automation_events(organization_id,event_type,entity_kind,entity_id,dedupe_key) values(%L,''payment.received'',''lead'',%L,''forged'')',org,source),'authenticated caller cannot forge domain event');
 perform pg_temp.automation_denied('select private.automation_tick(''forged'',10)','authenticated caller cannot execute worker');
 perform pg_temp.automation_assert((public.automation_test(org,(r->>'id')::uuid,current_setting('test.automation_event')::uuid)->>'matched')::boolean,'test mode matches authorized event');
 perform pg_temp.automation_assert((select count(*)=0 from public.automation_jobs),'test mode creates no jobs');
end$$;
reset role;
set local role business_os_worker;
select private.automation_tick('integration-test',100);
select private.automation_tick('integration-test',100);
reset role;
select pg_temp.automation_assert((select count(*)=1 from public.automation_jobs where status='succeeded'),'repeated worker tick executes action once');
select pg_temp.automation_assert((select count(*)=1 from public.notifications),'repeated worker tick creates one notification');
set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';n jsonb;id uuid;version integer;begin
 n=public.notifications_read(org);id=(n#>>'{rows,0,id}')::uuid;
 perform pg_temp.automation_assert((n->>'unread')::integer=1,'recipient sees unread notification');
 perform pg_temp.automation_assert(public.notification_target(org,id)->>'id'=current_setting('test.automation_source'),'notification resolves authorized live source');
 version=public.notification_state(org,id,1,'read');
 perform pg_temp.automation_assert(version=2 and public.notification_state(org,id,1,'read')=2,'duplicate mark-read is idempotent');
 perform pg_temp.automation_denied(format('select public.notification_state(%L,%L,1,''archived'')',org,id),'conflicting stale read-state update rejected');
 perform pg_temp.automation_assert(public.notification_state(org,id,2,'archived')=3,'archive preserves record with next version');
 perform pg_temp.automation_assert((public.notifications_read(org)->>'total')::integer=0,'archive removed from active view');
 perform pg_temp.automation_assert((public.notifications_read(org,1,'archived')->>'total')::integer=1,'archive remains available');
 perform pg_temp.automation_denied(format('select public.automation_retry(%L,%L)',org,(select j.id from public.automation_jobs j limit 1)),'successful action cannot be manually repeated');
 perform pg_temp.automation_denied(format('select public.notification_preferences_save(%L,0,''{"inApp":true,"email":true,"categories":[],"timezone":"Invalid/Zone","quietStart":null,"quietEnd":null}'')',org),'invalid timezone rejected by database');
 perform public.notification_preferences_save(org,0,'{"inApp":true,"email":true,"categories":["crm"],"timezone":"UTC","quietStart":null,"quietEnd":null}');
 perform pg_temp.automation_denied(format('select public.notification_preferences_save(%L,0,''{"inApp":true,"email":false,"categories":[],"timezone":"UTC","quietStart":null,"quietEnd":null}'')',org),'stale preference update rejected');
end$$;
reset role;
-- Change the rule to email and use another canonical event, preserving old execution facts.
set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';config jsonb;source uuid;begin
 select configuration into config from public.automation_rules where id=current_setting('test.automation_rule')::uuid;
 config=jsonb_set(config,'{actions,0,kind}','"email"');
 perform public.automation_configure(org,'template',0,'{"key":"operational_notice","subject":"Hello {{business_name}}","body":"Review {{entity_number}}"}');
 perform public.automation_rule_save(org,current_setting('test.automation_rule')::uuid,1,config);
 source=public.crm_save(org,'leads',jsonb_build_object('name','Email integration enquiry','phone','+12025550178','source_id',(select id from public.lead_sources where organization_id=org and active limit 1),'stage_id',(select id from public.crm_pipeline_stages where organization_id=org and active and outcome='open' order by sort_order limit 1)));
end$$;
reset role;
set local role business_os_worker;
select private.automation_tick('integration-test',100);
select set_config('test.email_claim',private.automation_email_claim(10)::text,true);
reset role;
do $$declare payload jsonb=current_setting('test.email_claim')::jsonb;begin
 perform pg_temp.automation_assert(jsonb_array_length(payload)=1,'restricted worker claims authorized opt-in email');
 perform pg_temp.automation_assert(payload#>>'{0,subject}' like 'Hello %','controlled email variables rendered');
 perform pg_temp.automation_assert((select count(*)=2 from public.automation_rule_versions where rule_id=current_setting('test.automation_rule')::uuid),'rule history preserves both revisions');
end$$;
set local role business_os_worker;
select set_config('test.email_duplicate',private.automation_email_claim(10)::text,true);
select private.automation_email_ack((current_setting('test.email_claim')::jsonb#>>'{0,id}')::uuid,(current_setting('test.email_claim')::jsonb#>>'{0,lease}')::uuid,'transient');
reset role;
select pg_temp.automation_assert(current_setting('test.email_duplicate')::jsonb='[]','live delivery lease prevents duplicate claim');
update public.email_deliveries set next_attempt_at=now() where id=(current_setting('test.email_claim')::jsonb#>>'{0,id}')::uuid;
set local role business_os_worker;
select set_config('test.email_retry',private.automation_email_claim(10)::text,true);
reset role;
select pg_temp.automation_assert(current_setting('test.email_claim')::jsonb#>>'{0,idempotencyKey}'=current_setting('test.email_retry')::jsonb#>>'{0,idempotencyKey}','delivery retry retains provider idempotency key');
select pg_temp.automation_assert(current_setting('test.email_claim')::jsonb#>>'{0,text}'=current_setting('test.email_retry')::jsonb#>>'{0,text}','delivery retry retains immutable email body');
select pg_temp.automation_assert(not private.automation_email_ack((current_setting('test.email_claim')::jsonb#>>'{0,id}')::uuid,(current_setting('test.email_claim')::jsonb#>>'{0,lease}')::uuid,'sent','stale-provider-id'),'stale lease cannot acknowledge delivery');
select pg_temp.automation_assert(private.automation_email_ack((current_setting('test.email_retry')::jsonb#>>'{0,id}')::uuid,(current_setting('test.email_retry')::jsonb#>>'{0,lease}')::uuid,'sent','fake-provider-id'),'current lease records delivery acknowledgement');
select pg_temp.automation_assert((select status='sent' and attempts=2 from public.email_deliveries limit 1),'delivery attempt history is retained');
select private.automation_retention();
set local request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';
set local role authenticated;
select pg_temp.automation_assert((select count(*)=0 from public.notifications),'different user cannot read recipient notification');
select pg_temp.automation_denied('select * from private.automation_email_payloads','email body storage is not browser readable');
reset role;
set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';config jsonb;source uuid;begin
 select configuration into config from public.automation_rules where id=current_setting('test.automation_rule')::uuid;
 config=jsonb_set(config,'{actions}',jsonb_build_array(jsonb_set(config#>'{actions,0}','{kind}','"followup"'),jsonb_set(config#>'{actions,0}','{kind}','"activity"')));
 perform public.automation_rule_save(org,null,0,config||'{"name":"Canonical followup and activity"}');
 source=public.crm_save(org,'leads',jsonb_build_object('name','Canonical action enquiry','phone','+12025550179','source_id',(select id from public.lead_sources where organization_id=org and active limit 1),'stage_id',(select id from public.crm_pipeline_stages where organization_id=org and active and outcome='open' order by sort_order limit 1)));
 perform set_config('test.canonical_action_source',source::text,true);
end$$;
reset role;set local role business_os_worker;
select private.automation_tick('canonical-actions',100);
select private.automation_tick('canonical-actions',100);
reset role;
select pg_temp.automation_assert((select count(*)=1 from public.lead_followups where lead_id=current_setting('test.canonical_action_source')::uuid),'repeated action creates one canonical CRM followup');
select pg_temp.automation_assert((select count(*)=1 from public.lead_activities where lead_id=current_setting('test.canonical_action_source')::uuid and activity_type='note'),'repeated action creates one canonical CRM activity');
delete from public.role_permissions where organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and permission_id=(select id from public.permissions where key='lead.view');
set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';set local role authenticated;
select pg_temp.automation_assert((public.notifications_read('dddddddd-dddd-4ddd-8ddd-dddddddddddd',1,'archived')->>'total')::integer=0,'optimized notification reads respect live source permission revocation');
select pg_temp.automation_assert((public.automation_read('dddddddd-dddd-4ddd-8ddd-dddddddddddd','history')->>'total')::integer=0,'optimized execution history respects live source permission revocation');
reset role;
rollback;

