\set ON_ERROR_STOP on
begin;
create function pg_temp.brochure_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end$$;
create function pg_temp.brochure_denied(statement text,label text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege or check_violation or invalid_parameter_value or serialization_failure or unique_violation or foreign_key_violation then raise notice 'PASS: %',label;return;end;raise exception 'FAIL: %',label;end$$;
create function pg_temp.brochure_signature(body jsonb) returns text language sql security definer as $$select encode(extensions.hmac(convert_to(body::text,'UTF8'),convert_to('phase9-test-key-not-a-production-secret-123456','UTF8'),'sha256'),'hex');$$;
create function pg_temp.brochure_proof(purpose text,b uuid,version integer,doc jsonb,restore uuid default null) returns jsonb language sql security definer as $$select jsonb_build_object('keyId','phase9-test','purpose',purpose,'organizationId','dddddddd-dddd-4ddd-8ddd-dddddddddddd','brochureId',b,'version',version,'document',doc,'expiresAt',now()+interval '5 minutes','slug','phase9-test','template','','restoreId',restore,'businessName','Demo Interiors','draftDigest',case when b is null then null else public.brochure_document_digest('dddddddd-dddd-4ddd-8ddd-dddddddddddd',b) end,'pdfDigest',encode(extensions.digest(convert_to('%PDF-'||repeat('x',100),'UTF8'),'sha256'),'hex'));$$;
create function pg_temp.brochure_hash(value text) returns text language sql security definer as $$select encode(extensions.digest(convert_to(value,'UTF8'),'sha256'),'hex');$$;
insert into private.website_build_keys(key_id,secret) values('phase9-test',convert_to('phase9-test-key-not-a-production-secret-123456','UTF8')) on conflict(key_id) do update set secret=excluded.secret,active=true;
insert into public.organization_entitlements(organization_id,module_id,enabled,source,configuration) select 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',id,true,'manual','{"analytics":true,"count":20,"pages":50,"public_share":true}' from public.modules where key='brochure' on conflict(organization_id,module_id,source) do update set enabled=true,configuration=excluded.configuration;
insert into public.organization_entitlements(organization_id,module_id,enabled,source) select 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',id,false,'manual' from public.modules where key='website' on conflict(organization_id,module_id,source) do update set enabled=false;
select set_config('test.brochure_document',/*DOCUMENT*/::text,true);
set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';b uuid;copy uuid;doc jsonb=current_setting('test.brochure_document')::jsonb;proof jsonb;r jsonb;v1 uuid;v2 uuid;v3 uuid;restored uuid;asset1 uuid;asset2 uuid;pdf text=encode(convert_to('%PDF-'||repeat('x',100),'UTF8'),'base64');next integer;begin
 perform pg_temp.brochure_assert(not public.has_entitlement(org,'website') and public.has_entitlement(org,'brochure'),'Brochure enabled with Website disabled');
 proof=pg_temp.brochure_proof('brochure.save',null,0,doc);r=public.brochure_write(org,null,0,proof::text,pg_temp.brochure_signature(proof));b=(r->>'id')::uuid;perform set_config('test.brochure_id',b::text,true);
 perform pg_temp.brochure_assert(public.brochure_read(org,b)->>'name'='Brochure version one','brochure created without website');
 perform pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test') is null,'draft brochure not publicly readable');
 perform pg_temp.brochure_denied(format('select document from public.brochures where id=%L',b),'raw draft columns protected');
 perform pg_temp.brochure_denied(format('select public.brochure_write(%L,null,0,%L,%L)',org,proof::text,pg_temp.brochure_signature(proof)),'duplicate slug denied');
 proof=pg_temp.brochure_proof('brochure.publish',b,1,doc);
 perform pg_temp.brochure_denied(format('select public.brochure_publish(%L,%L,1,%L,''forged'',%L,''bad'')',org,b,proof::text,pdf),'forged publication proof denied');
 perform pg_temp.brochure_denied(format('select public.brochure_publish(%L,%L,1,%L,%L,%L,''bad'')',org,b,proof::text,pg_temp.brochure_signature(proof),encode(convert_to('%PDF-'||repeat('y',100),'UTF8'),'base64')),'PDF digest mismatch denied atomically');
 perform pg_temp.brochure_assert(jsonb_array_length(public.brochure_read(org,b)->'versions')=0,'failed publication creates no version');
 v1=public.brochure_publish(org,b,1,proof::text,pg_temp.brochure_signature(proof),pdf,'First publication');perform set_config('test.brochure_v1',v1::text,true);
 perform pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test')->>'sequence'='1','public publication resolves without Website');
 perform pg_temp.brochure_assert(not public.brochure_public('demo-interiors','phase9-test') ? 'organizationId' and not public.brochure_public('demo-interiors','phase9-test') ? 'id','public projection excludes private brochure and tenant IDs');
 perform pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test','pdf')->>'data'=pdf,'published PDF bytes returned unchanged');
 perform pg_temp.brochure_assert(public.brochure_public('other-business','phase9-test') is null,'foreign business slug cannot resolve brochure');
 doc=jsonb_set(doc,'{pages,0,components,0,text}','"Draft second edition"');proof=pg_temp.brochure_proof('brochure.save',b,2,doc);r=public.brochure_write(org,b,2,proof::text,pg_temp.brochure_signature(proof));
 perform pg_temp.brochure_assert(r->>'version'='3','saving increments optimistic revision');
 perform pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test')->'document'->'pages'->0->'components'->0->>'text'='Version one','draft edits never replace published version');
 perform pg_temp.brochure_denied(format('select public.brochure_write(%L,%L,2,%L,%L)',org,b,proof::text,pg_temp.brochure_signature(proof)),'stale draft save denied');
 proof=pg_temp.brochure_proof('brochure.publish',b,3,doc);v2=public.brochure_publish(org,b,3,proof::text,pg_temp.brochure_signature(proof),pdf,'Second edition');
 doc=jsonb_set(doc,'{pages,0,components,0,text}','"Third edition"');proof=pg_temp.brochure_proof('brochure.save',b,4,doc);perform public.brochure_write(org,b,4,proof::text,pg_temp.brochure_signature(proof));proof=pg_temp.brochure_proof('brochure.publish',b,5,doc);v3=public.brochure_publish(org,b,5,proof::text,pg_temp.brochure_signature(proof),pdf,'Third edition');
 proof=pg_temp.brochure_proof('brochure.publish',b,6,current_setting('test.brochure_document')::jsonb,v1);restored=public.brochure_publish(org,b,6,proof::text,pg_temp.brochure_signature(proof),'','Restore one',v1);
 perform pg_temp.brochure_assert(restored<>v1 and public.brochure_public('demo-interiors','phase9-test')->>'sequence'='4','restore creates Version 4');
 perform pg_temp.brochure_assert(public.brochure_read(org,b,v1)->'document'->'pages'->0->'components'->0->>'text'='Version one' and public.brochure_read(org,b,v2)->'document'->'pages'->0->'components'->0->>'text'='Draft second edition' and public.brochure_read(org,b,v3)->'document'->'pages'->0->'components'->0->>'text'='Third edition','Versions 1 through 3 remain unchanged');
 perform pg_temp.brochure_assert(public.brochure_pdf_read(org,b,v1)->>'data'=pdf,'historical PDF remains byte-stable');
 proof=pg_temp.brochure_proof('brochure.publish',b,7,doc,v1);perform pg_temp.brochure_denied(format('select public.brochure_publish(%L,%L,7,%L,%L,'''',''bad restore'',%L)',org,b,proof::text,pg_temp.brochure_signature(proof),v1),'restore cannot substitute modified content');
 proof=jsonb_build_object('keyId','phase9-test','purpose','brochure.asset','organizationId',org,'expiresAt',now()+interval '5 minutes','name','Original logo','mime','image/webp','width',500,'height',500,'alt','Original logo','digest',pg_temp.brochure_hash('first-image'));
 asset1=(public.brochure_media(org,'upload',null,proof::text,pg_temp.brochure_signature(proof),encode(convert_to('first-image','UTF8'),'base64'))->>'id')::uuid;
 perform pg_temp.brochure_assert((public.brochure_media(org,'upload',null,proof::text,pg_temp.brochure_signature(proof),encode(convert_to('first-image','UTF8'),'base64'))->>'id')::uuid=asset1,'identical image reuses existing private storage');
 perform set_config('test.brochure_asset',asset1::text,true);
 doc=jsonb_set(doc,'{pages,0,components,0,asset}',to_jsonb(asset1::text));proof=pg_temp.brochure_proof('brochure.save',b,7,doc);perform public.brochure_write(org,b,7,proof::text,pg_temp.brochure_signature(proof));proof=pg_temp.brochure_proof('brochure.publish',b,8,doc);v2=public.brochure_publish(org,b,8,proof::text,pg_temp.brochure_signature(proof),pdf,'Original image');
 perform pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test','asset',asset1)->>'data'=encode(convert_to('first-image','UTF8'),'base64'),'published image resolves with Website disabled');
 perform pg_temp.brochure_denied(format('select public.brochure_media(%L,''archive'',%L)',org,asset1),'referenced image cannot be archived');
 perform pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test','asset','00000000-0000-4000-8000-000000000099') is null,'unreferenced asset remains private');
 doc=jsonb_set(doc,'{form,enabled}','true');proof=pg_temp.brochure_proof('brochure.save',b,9,doc);perform public.brochure_write(org,b,9,proof::text,pg_temp.brochure_signature(proof));proof=pg_temp.brochure_proof('brochure.publish',b,10,doc);perform public.brochure_publish(org,b,10,proof::text,pg_temp.brochure_signature(proof),pdf,'Consultation form');
 perform pg_temp.brochure_denied($q$select public.brochure_submit_lead('demo-interiors','phase9-test','cover','{"name":"Visitor","phone":"+919876543201","consent":false}')$q$,'brochure form requires explicit consent');
 perform pg_temp.brochure_denied($q$select public.brochure_submit_lead('demo-interiors','phase9-test','missing','{"name":"Visitor","phone":"+919876543201","consent":true}')$q$,'missing form page denied');
 perform pg_temp.brochure_denied($q$select public.brochure_submit_lead('demo-interiors','phase9-test','cover','{"name":"Visitor","phone":"+919876543201","consent":true,"internal_cost":"1"}')$q$,'unconfigured form fields denied');
 r=public.brochure_submit_lead('demo-interiors','phase9-test','cover','{"name":"Brochure visitor","phone":"+91 98765 43201","consent":true}');perform pg_temp.brochure_assert(r->>'accepted'='true' and not r ? 'id','brochure creates canonical lead without exposing ID');
 perform public.brochure_submit_lead('demo-interiors','phase9-test','cover','{"name":"Repeat visitor","phone":"+919876543201","consent":true}');
 perform pg_temp.brochure_assert((select count(*)=1 from public.leads where organization_id=org and phone_normalized='+919876543201'),'brochure duplicate detection reuses canonical lead');
 perform pg_temp.brochure_assert((select count(*)=2 from public.lead_activities where organization_id=org and metadata->>'brochure'=b::text and metadata->>'page'='cover' and metadata->>'consent'='true'),'CRM activities retain brochure version page CTA and consent');
 perform public.brochure_submit_lead('demo-interiors','phase9-test','cover','{}','bot');perform pg_temp.brochure_assert((select count(*)=1 from public.leads where organization_id=org and phone_normalized='+919876543201'),'honeypot creates no extra lead');
 perform pg_temp.brochure_assert(jsonb_array_length(public.brochure_metrics_read(org,b))>0,'aggregate brochure metrics recorded without visitor identity');
 proof=pg_temp.brochure_proof('brochure.save',null,0,doc)||'{"slug":"phase9-copy"}';copy=(public.brochure_write(org,null,0,proof::text,pg_temp.brochure_signature(proof))->>'id')::uuid;
 perform pg_temp.brochure_assert(public.brochure_read(org,copy)->>'status'='draft' and jsonb_array_length(public.brochure_read(org,copy)->'versions')=0,'duplication copies design into a new draft without version history');
 perform pg_temp.brochure_denied(format('select public.brochure_read(%L,%L,%L)',org,copy,v1),'cross-brochure historical version denied');
 perform pg_temp.brochure_denied(format('select public.brochure_pdf_read(%L,%L,%L)',org,copy,v1),'cross-brochure private PDF denied');
 perform public.brochure_status(org,b,11,'unpublished');perform pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test') is null and public.brochure_public('demo-interiors','phase9-test','pdf') is null,'unpublishing revokes viewer and PDF');
 perform public.brochure_status(org,b,12,'archived');perform pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test') is null,'archived brochure is not public');proof=pg_temp.brochure_proof('brochure.save',b,13,doc);perform pg_temp.brochure_denied(format('select public.brochure_write(%L,%L,13,%L,%L)',org,b,proof::text,pg_temp.brochure_signature(proof)),'archived brochure cannot be edited');perform public.brochure_status(org,b,13,'draft');
 proof=pg_temp.brochure_proof('brochure.publish',b,14,doc);perform public.brochure_publish(org,b,14,proof::text,pg_temp.brochure_signature(proof),pdf,'Republished');
 perform public.brochure_grant_designer(org,'33333333-3333-4333-8333-333333333333');
 perform pg_temp.brochure_denied(format('select public.brochure_read(''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',%L)',b),'foreign tenant cannot read brochure');
 perform pg_temp.brochure_denied(format('select public.brochure_asset_read(''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',%L,%L)',b,asset1),'foreign tenant cannot read image');
end$$;
reset role;
select pg_temp.brochure_denied('update public.brochure_versions set summary=''tampered'' where id='''||current_setting('test.brochure_v1')||'''','historical version protected even from accidental privileged update');
-- Resolve approved brand assets only for a bound draft; never widen old snapshots.
insert into public.marketing_kits(organization_id,content) values('dddddddd-dddd-4ddd-8ddd-dddddddddddd',jsonb_build_object('brand',jsonb_build_object('logo',current_setting('test.brochure_asset')),'content','[]'::jsonb))
on conflict(organization_id) do update set content=excluded.content;
update public.brochures set document=jsonb_set(document,'{pages,0,components}',jsonb_build_array(jsonb_build_object('id','boundLogo','type','logo','binding','logo'))) where slug='phase9-copy';
set local role authenticated;
select pg_temp.brochure_assert(public.brochure_asset_read('dddddddd-dddd-4ddd-8ddd-dddddddddddd',(select id from public.brochures where slug='phase9-copy'),current_setting('test.brochure_asset')::uuid)->>'data' is not null,'draft preview resolves its bound brand logo');
select pg_temp.brochure_denied('select public.brochure_asset_read(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'','''||current_setting('test.brochure_id')||''','''||current_setting('test.brochure_asset')||''','''||current_setting('test.brochure_v1')||''')','brand changes cannot widen historical asset access');
reset role;
update public.brochures set document=jsonb_set(document,'{pages,0,components}','[]'::jsonb) where slug='phase9-copy';
set local role authenticated;
select pg_temp.brochure_denied('select public.brochure_asset_read(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',(select id from public.brochures where slug=''phase9-copy''),'''||current_setting('test.brochure_asset')||''')','unbound brand images remain unavailable through draft preview');
reset role;
select pg_temp.brochure_denied('update private.brochure_pdfs set data=convert_to(''tampered'',''UTF8'') where version_id='''||current_setting('test.brochure_v1')||'''','historical PDF bytes immutable');
insert into private.brochure_form_limits(brochure_id,bucket,hits) values(current_setting('test.brochure_id')::uuid,date_trunc('minute',now()),60) on conflict(brochure_id,bucket) do update set hits=60;
set local role anon;
select pg_temp.brochure_assert(public.brochure_submit_lead('demo-interiors','phase9-test','cover','{"name":"Rate limited","phone":"+919876543202","consent":true}')->>'accepted'='false','brochure form rate limit rejects above quota');
select pg_temp.brochure_denied('select id from public.brochures','anonymous raw brochure enumeration denied');
select pg_temp.brochure_denied('select public.brochure_read(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'')','anonymous management RPC denied');
reset role;
delete from public.membership_roles where membership_id in(select id from public.organization_memberships where user_id='33333333-3333-4333-8333-333333333333') and role_id not in(select id from public.roles where key='brochure_designer');
set local request.jwt.claim.sub='33333333-3333-4333-8333-333333333333';set local role authenticated;
select pg_temp.brochure_assert(public.brochure_read('dddddddd-dddd-4ddd-8ddd-dddddddddddd',current_setting('test.brochure_id')::uuid)->>'name'='Brochure version one','Brochure Designer can read organization brochures');
select pg_temp.brochure_assert(not private.has_permission('dddddddd-dddd-4ddd-8ddd-dddddddddddd','website.view') and not private.has_permission('dddddddd-dddd-4ddd-8ddd-dddddddddddd','contract.view') and not private.has_permission('dddddddd-dddd-4ddd-8ddd-dddddddddddd','customer.view'),'Brochure Designer receives no Website or private commercial grants');
reset role;
update public.brochures set status='suspended' where id=current_setting('test.brochure_id')::uuid;
set local role anon;select pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test') is null,'platform suspension revokes public brochure');reset role;
update public.brochures set status='published' where id=current_setting('test.brochure_id')::uuid;
update public.organization_entitlements set enabled=false where organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and module_id in(select id from public.modules where key='brochure');
set local role authenticated;
select pg_temp.brochure_denied('select public.brochure_read(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'')','brochure entitlement revocation blocks management');
select pg_temp.brochure_denied('select public.brochure_pdf_read(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'','''||current_setting('test.brochure_id')||''','''||current_setting('test.brochure_v1')||''')','brochure entitlement revocation blocks internal PDF');
select pg_temp.brochure_assert(public.brochure_public('demo-interiors','phase9-test') is null,'brochure entitlement revocation blocks published viewer');
select pg_temp.brochure_assert(public.has_entitlement('dddddddd-dddd-4ddd-8ddd-dddddddddddd','projects'),'brochure revocation leaves Projects enabled');
reset role;rollback;
