begin;
create function pg_temp.crm_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end$$;
create function pg_temp.crm_denied(statement text,label text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege or check_violation or invalid_parameter_value or foreign_key_violation or serialization_failure or unique_violation then raise notice 'PASS: %',label;return;end;raise exception 'FAIL: %',label;end$$;
set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';lead uuid;followup uuid;visit uuid;version integer;converted jsonb;again jsonb;t text;begin
 perform pg_temp.crm_assert((public.crm_search(org,'lead_sources')->>'total')::integer>=13,'configurable sources');
 lead=public.crm_save(org,'leads',jsonb_build_object('name','CRM verification','phone','+44 (20) 7946 0958','email','crm@example.test','source_id',(select id from public.lead_sources where organization_id=org and key='referral'),'stage_id',(select id from public.crm_pipeline_stages where organization_id=org and key='new'),'assigned_to',auth.uid()));
 perform pg_temp.crm_assert((select phone_normalized='+442079460958' and lead_number like 'L-%' from public.leads where id=lead),'lead numbering and international phone');
 perform pg_temp.crm_assert(jsonb_array_length(public.crm_duplicates(org,'0044 20 7946 0958','')->'leads')=1,'tenant-local normalized duplicate warning');
 perform pg_temp.crm_denied(format('select public.crm_save(%L,''leads'',%L::jsonb)',org,jsonb_build_object('id',lead,'version',999,'name','stale')),'stale lead denied');
 perform pg_temp.crm_denied(format('select public.crm_command(%L,''assign'',%L::jsonb)',org,jsonb_build_object('id',lead,'version',1,'assigned_to','55555555-5555-4555-8555-555555555555')),'cross-tenant employee assignment denied');
 followup=public.crm_save(org,'lead_followups',jsonb_build_object('lead_id',lead,'assigned_to',auth.uid(),'due_at',now()-interval '1 hour','followup_type','call','note','Call back'));
 perform pg_temp.crm_assert((select next_follow_up_at<now() from public.leads where id=lead),'pending follow-up drives due date');
 perform pg_temp.crm_assert((public.crm_search(org,'lead_followups',jsonb_build_object('lead_id',lead,'queue','overdue','status','pending'))->>'total')::integer=1,'overdue queue');
 perform public.crm_command(org,'followup',jsonb_build_object('id',followup,'version',1,'status','completed','outcome','Discussed scope'));
 perform public.crm_command(org,'followup',jsonb_build_object('id',followup,'version',1,'status','completed'));
 perform pg_temp.crm_assert((select lead_followups.version=2 from public.lead_followups where id=followup),'follow-up completion is idempotent');
 perform pg_temp.crm_assert((select next_follow_up_at is null from public.leads where id=lead),'completed follow-up clears queue');
 visit=public.crm_save(org,'site_visits',jsonb_build_object('lead_id',lead,'assigned_to',auth.uid(),'scheduled_at',now(),'site_address','{"line1":"Site","line2":"","city":"","region":"","postal_code":"","country_code":"GB"}'::jsonb));
 perform public.crm_command(org,'visit',jsonb_build_object('id',visit,'version',1,'status','completed','notes','Access via lift','outcome','Requirements recorded'));
 perform pg_temp.crm_assert((select completed_at is not null and status='completed' from public.site_visits where id=visit),'site visit completion');
 perform public.crm_save(org,'lead_activities',jsonb_build_object('lead_id',lead,'activity_type','phone_call','body','Manual call note'));
 perform pg_temp.crm_denied(format('select public.crm_save(%L,''lead_activities'',%L::jsonb)',org,jsonb_build_object('lead_id',lead,'activity_type','customer_response','body','forged')),'manual system activity rejected');
 select l.version into version from public.leads l where id=lead;
 perform pg_temp.crm_denied(format('select public.crm_command(%L,''stage'',%L::jsonb)',org,jsonb_build_object('id',lead,'version',version,'stage_id',(select id from public.crm_pipeline_stages where organization_id=org and key='lost'))),'Lost requires reason');
 perform pg_temp.crm_denied(format('select public.crm_convert(%L,%L::jsonb)',org,jsonb_build_object('id',lead,'version',version,'project_id','99999999-9999-4999-8999-999999999999')),'conversion rolls back unavailable project');
 perform pg_temp.crm_assert(not exists(select 1 from public.customers where organization_id=org and email='crm@example.test'),'failed conversion creates no customer');
 converted=public.crm_convert(org,jsonb_build_object('id',lead,'version',version,'project_name','CRM project'));
 again=public.crm_convert(org,jsonb_build_object('id',lead,'version',version));
 perform pg_temp.crm_assert(converted=again,'conversion retry returns original mapping');
 perform pg_temp.crm_assert((select project_id=(converted->>'project_id')::uuid from public.site_visits where id=visit),'site visit history survives conversion');
 perform pg_temp.crm_assert((select count(*)=1 from public.lead_activities where lead_id=lead and activity_type='conversion'),'single conversion event');
 perform pg_temp.crm_assert((select count(*)=1 from public.customers where organization_id=org and email='crm@example.test'),'one converted customer');
 perform pg_temp.crm_assert((select count(*)>0 from public.lead_activities where lead_id=lead),'timeline retained');
 foreach t in array array['lead_sources','crm_pipeline_stages','crm_lost_reasons','crm_requirement_fields','leads','lead_activities','lead_followups','site_visits','quotation_share_links','quotation_customer_responses'] loop
  perform pg_temp.crm_denied(format('delete from public.%I where organization_id=%L',t,org),'direct DML denied: '||t);
 end loop;
 perform pg_temp.crm_assert(not has_table_privilege('authenticated','private.quotation_share_secrets','select'),'share hashes inaccessible to business role');
 perform pg_temp.crm_denied($q$select public.public_quotation(repeat('0',64))$q$,'invalid token denied');
end$$;

do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';source uuid;stage uuid;lead uuid;lead2 uuid;customer uuid;mapping jsonb;begin
 source=public.crm_save(org,'lead_sources','{"name":"Partner campaign","key":"test_partner","active":true,"sort_order":100}');
 perform public.crm_save(org,'lead_sources',jsonb_build_object('id',source,'version',1,'name','Partner referral'));
 perform pg_temp.crm_assert((select name='Partner referral' and version=2 from public.lead_sources where id=source),'source create and edit');
 stage=public.crm_save(org,'crm_pipeline_stages','{"name":"Needs design","key":"test_design","active":true,"sort_order":100,"outcome":"open"}');
 perform public.crm_save(org,'crm_pipeline_stages',jsonb_build_object('id',stage,'version',1,'name','Design discussion'));
 lead=public.crm_save(org,'leads',jsonb_build_object('name','Existing master conversion','phone','+61255550123','source_id',source,'stage_id',stage));
 perform pg_temp.crm_assert((select stage_id=stage from public.leads where id=lead),'custom pipeline stage used');
 perform pg_temp.crm_denied(format('select public.crm_save(%L,''crm_pipeline_stages'',%L::jsonb)',org,jsonb_build_object('id',stage,'version',2,'outcome','won')),'referenced stage semantics protected');
 select id into customer from public.customers where organization_id=org order by created_at,id limit 1;
 mapping=public.crm_convert(org,jsonb_build_object('id',lead,'version',1,'customer_id',customer));
 perform pg_temp.crm_assert((mapping->>'customer_id')::uuid=customer,'conversion links existing customer');
 perform pg_temp.crm_assert((select customer_id=customer from public.projects where id=(mapping->>'project_id')::uuid),'converted project links selected customer');
 lead2=public.crm_save(org,'leads',jsonb_build_object('name','Existing project conversion','phone','+61255550124','source_id',source,'stage_id',stage));
 perform pg_temp.crm_denied(format('select public.crm_convert(%L,%L::jsonb)',org,jsonb_build_object('id',lead2,'version',1,'customer_id',customer,'project_id',mapping->>'project_id')),'project cannot acquire second originating lead');
 perform public.crm_command(org,'stage',jsonb_build_object('id',lead2,'version',1,'stage_id',(select id from public.crm_pipeline_stages where organization_id=org and key='lost'),'lost_reason_id',(select id from public.crm_lost_reasons where organization_id=org and key='budget_mismatch'),'note','Outside budget'));
 perform pg_temp.crm_assert((select lifecycle='lost' and lost_at is not null and lost_by=auth.uid() from public.leads where id=lead2),'Lost records reason and actor');
 perform public.crm_save(org,'lead_sources',jsonb_build_object('id',source,'version',2,'active',false));
 perform pg_temp.crm_denied(format('select public.crm_save(%L,''leads'',%L::jsonb)',org,jsonb_build_object('name','Inactive source lead','phone','+61255550125','source_id',source,'stage_id',stage)),'inactive source cannot receive new leads');
 perform pg_temp.crm_assert((select source_id=source from public.leads where id=lead),'source deactivation preserves lead history');
 perform public.crm_save(org,'leads',jsonb_build_object('id',lead,'version',2,'source_id',source,'notes','Updated after source deactivation'));
 perform pg_temp.crm_assert((select notes='Updated after source deactivation' from public.leads where id=lead),'existing inactive-source lead remains editable');
end$$;
reset role;
do $$declare t text;begin foreach t in array array['lead_sources','crm_pipeline_stages','crm_lost_reasons','crm_requirement_fields','leads','lead_activities','lead_followups','site_visits','quotation_share_links','quotation_customer_responses'] loop perform pg_temp.crm_assert((select relrowsecurity and relforcerowsecurity from pg_class where oid=('public.'||t)::regclass),'forced RLS: '||t);end loop;end$$;
set local request.jwt.claim.sub='55555555-5555-4555-8555-555555555555';
set local role authenticated;
do $$declare t text;count_rows integer;begin foreach t in array array['lead_sources','crm_pipeline_stages','crm_lost_reasons','crm_requirement_fields','leads','lead_activities','lead_followups','site_visits','quotation_share_links','quotation_customer_responses'] loop execute format('select count(*) from public.%I',t) into count_rows;perform pg_temp.crm_assert(count_rows=0,'nonmember cannot read: '||t);end loop;
perform pg_temp.crm_denied($q$select public.crm_convert('dddddddd-dddd-4ddd-8ddd-dddddddddddd','{}')$q$,'nonmember conversion denied');
foreach t in array array['leads','lead_activities','lead_followups','site_visits','lead_sources','crm_pipeline_stages'] loop
 perform pg_temp.crm_denied(format('select public.crm_save(%L,%L,%L::jsonb)','dddddddd-dddd-4ddd-8ddd-dddddddddddd',t,'{}'),'nonmember mutation denied: '||t);
end loop;
perform pg_temp.crm_denied($q$select public.crm_command('dddddddd-dddd-4ddd-8ddd-dddddddddddd','assign','{}')$q$,'nonmember assignment denied');
perform pg_temp.crm_denied($q$select public.quotation_share_manage('dddddddd-dddd-4ddd-8ddd-dddddddddddd','create','{}')$q$,'nonmember share management denied');
end$$;
reset role;
rollback;

