begin;
create function pg_temp.execution_assert(ok boolean,label text) returns void language plpgsql as $$begin
 if ok is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;
end$$;
create function pg_temp.execution_denied(statement text,label text) returns void language plpgsql as $$begin
 begin execute statement;exception when insufficient_privilege or check_violation or invalid_parameter_value or serialization_failure then raise notice 'PASS: %',label;return;end;
 raise exception 'FAIL: %',label;
end$$;
do $$declare q jsonb;begin
 q=private.execution_quantity('{"basis":"finished_area","factor":"2"}','{"finished_area":"80"}','{"consumption_per_purchase":"32","purchase_increment":"1"}','10');
 perform pg_temp.execution_assert(q->>'base_quantity'='160' and q->>'waste_quantity'='16' and q->>'required_quantity'='176' and q->>'calculated_purchase_quantity'='5.5' and q->>'planned_purchase_quantity'='6','area conversion applies waste before whole-sheet rounding');
 q=private.execution_quantity('{"basis":"volume","factor":"1.5"}','{"width":"2","height":"3","length":"4"}','{"consumption_per_purchase":"1","purchase_increment":"0.25"}','5');
 perform pg_temp.execution_assert(q->>'base_quantity'='36' and q->>'required_quantity'='37.8' and q->>'planned_purchase_quantity'='38','construction volume basis supports fractional pack increments');
 q=private.execution_quantity('{"basis":"fixed","factor":"1.000001"}','{}','{"consumption_per_purchase":"1","purchase_increment":"1"}','0','3');
 perform pg_temp.execution_assert(q->>'rounded_purchase_quantity'='2' and q->>'override_quantity'='3' and q->>'planned_purchase_quantity'='3','calculated and overridden quantities remain distinct');
 q=private.execution_quantity('{"basis":"fixed","factor":"999999999999999998"}','{}','{"consumption_per_purchase":"999999999999999997","purchase_increment":"1"}','0');
 perform pg_temp.execution_assert(q->>'rounded_purchase_quantity'='2','tiny division remainder cannot disappear at large magnitude');
 perform pg_temp.execution_denied($s$select private.execution_quantity('{"basis":"eval","factor":"1"}','{}','{"consumption_per_purchase":"1","purchase_increment":"1"}','0')$s$,'arbitrary formula basis rejected');
 perform pg_temp.execution_denied($s$select private.execution_quantity('{"basis":"fixed","factor":"1","code":"alert(1)"}','{}','{"consumption_per_purchase":"1","purchase_increment":"1"}','0')$s$,'stored executable formula field rejected');
 perform pg_temp.execution_denied($s$select private.execution_quantity('{"basis":"fixed","factor":"1"}','{}','{"consumption_per_purchase":"0","purchase_increment":"1"}','0')$s$,'zero conversion rejected');
 perform pg_temp.execution_denied($s$select private.execution_quantity('{"basis":"fixed","factor":"1"}','{}','{"consumption_per_purchase":"1","purchase_increment":"0.5"}','0','1.1')$s$,'override outside pack increment rejected');
 perform pg_temp.execution_denied($s$select private.execution_quantity('{"basis":"fixed","factor":"1"}','{}','{"consumption_per_purchase":"1","purchase_increment":"1"}','101')$s$,'waste over limit rejected');
end$$;
set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
insert into private.quotation_signing_keys(singleton,secret_hex) values(true,repeat('a',64)) on conflict(singleton) do nothing;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';customer uuid;project uuid;root uuid=gen_random_uuid();revision uuid=gen_random_uuid();share jsonb;snapshot jsonb;begin
 select id,customer_id into project,customer from public.projects where organization_id=org order by id limit 1;
 snapshot=jsonb_build_object('snapshot_version',1,'name','Original wardrobe','line_type','manual','quantity','1','unit',jsonb_build_object('key','each','label','Each'),'display_rate','1000','effective_amount','1000','final_amount','1000','discount_amount','0','minimum_amount',null,'customer_specifications','[]'::jsonb);
 insert into public.quotations(id,organization_id,customer_id,project_id,quotation_number) values(root,org,customer,project,'EXECUTION-TEST');
 insert into public.quotation_revisions(id,organization_id,quotation_id,project_id,revision_number,currency,valid_until,document_snapshot) select revision,org,root,project,1,'INR',current_date+30,jsonb_build_object('branding',branding,'customer',jsonb_build_object('name','Execution Customer','billing_address','{}'::jsonb),'project',jsonb_build_object('name','Execution Project','site_address','{}'::jsonb),'display',jsonb_build_object('quantity',true,'unit_rate',true,'specifications',true)) from public.organization_quotation_settings where organization_id=org;
 insert into public.quotation_items(organization_id,revision_id,project_id,snapshot) values(org,revision,project,snapshot);
 update public.quotation_revisions set status='issued',issued_at=now(),totals=private.quotation_totals(id,discount) where id=revision;
 update public.quotations set status='issued',current_revision_id=revision where id=root;
 share=public.quotation_share_manage(org,'create',jsonb_build_object('revision_id',revision));
 perform public.public_quotation(share->>'token','respond','{"action":"approved","name":"Execution Customer","acknowledged":true}');
end$$;
insert into public.organization_entitlements(organization_id,module_id,enabled,source) select 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',id,true,'manual' from public.modules where key in ('purchasing','vendors');
set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';category uuid;material uuid;variant uuid;conversion uuid;rate uuid;recipe uuid;recipe_item uuid;begin
 category=public.execution_configure(org,'material_categories','{"name":"Boards","code":"TEST-BOARDS"}');
 material=public.execution_configure(org,'materials',jsonb_build_object('category_id',category,'name','Plywood','code','TEST-PLY'));
 variant=public.execution_configure(org,'material_variants',jsonb_build_object('material_id',material,'name','18 mm','code','TEST-PLY-18','default_waste','10'));
 conversion=public.execution_configure(org,'material_unit_conversions',jsonb_build_object('variant_id',variant,'purchase_unit','sheet','consumption_unit','sqft','consumption_per_purchase','32','purchase_increment','1','reason','Explicit 8 by 4 sheet conversion'));
 perform pg_temp.execution_assert((select active_conversion_id=conversion and version=2 from public.material_variants where id=variant),'material conversion revision becomes active');
 rate=public.execution_cost_record(org,jsonb_build_object('variant_id',variant,'currency','INR','unit_cost','2500','source_reference','Test planning rate','valid_from',current_date));
 perform pg_temp.execution_assert((select unit_cost='2500' from public.material_cost_revisions where id=rate),'effective material cost stored separately');
 recipe=public.execution_configure(org,'estimation_recipes','{"name":"Wardrobe recipe","matching":{"item_key":"wardrobe"}}');
 recipe_item=public.execution_configure(org,'estimation_recipe_items',jsonb_build_object('recipe_id',recipe,'variant_id',variant,'cost_kind','material','description','Carcass boards','rule',jsonb_build_object('basis','finished_area','factor','2'),'sort_order',0));
 perform public.execution_configure(org,'estimation_recipe_items',jsonb_build_object('id',recipe_item,'version',1,'description','Carcass and shelves'));
 perform pg_temp.execution_assert((select version=2 from public.estimation_recipe_items where id=recipe_item),'recipe item supports optimistic versioned configuration');
 perform pg_temp.execution_denied(format('select public.execution_configure(%L,''estimation_recipe_items'',%L)',org,jsonb_build_object('id',recipe_item,'version',1,'description','Stale edit')),'stale recipe edit rejected');
end$$;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';contract uuid;revision uuid;successor uuid;s uuid;v integer;line uuid;payload jsonb;pr uuid;pr_input jsonb;vendor uuid;rfq uuid;rfq_input jsonb;quote uuid;quote_input jsonb;po1 uuid;po2 uuid;competing_po uuid;po_input jsonb;quote_item uuid;receipt uuid;receipt_input jsonb;po_item uuid;report jsonb;begin
 select public.contract_create(org,r.id) into contract from public.quotation_revisions r join public.quotations q on q.id=r.quotation_id where q.quotation_number='EXECUTION-TEST';
 if contract is null then raise exception 'Execution tests require an accepted contract fixture';end if;
 revision=public.execution_estimate_command(org,'create',jsonb_build_object('contract_id',contract));
 perform pg_temp.execution_assert(revision=public.execution_estimate_command(org,'create',jsonb_build_object('contract_id',contract)),'estimate creation retry returns open revision');
 perform pg_temp.execution_assert((public.execution_scope(org,contract)->>'total')::integer>0,'accepted contract produces physical execution scope');
 perform pg_temp.execution_denied(format('select public.execution_estimate_command(%L,''submit'',%L)',org,jsonb_build_object('id',revision,'version',1)),'unestimated active scope blocks submission');
 select id into s from public.execution_estimate_scope_items where revision_id=revision and coverage='unestimated' order by id limit 1;
 payload=jsonb_build_object('version',1,'scope_id',s,'method','manual','cost_kind','labour','description','Installation labour','unit','hour','rule',jsonb_build_object('basis','fixed','factor','2.5'),'manual_cost',jsonb_build_object('unit_cost','100.25','source_reference','Internal labour schedule','reason','Approved planning assumption'));
 line=public.execution_line_save(org,revision,payload);
 perform pg_temp.execution_assert((select base_quantity='2.5' and planned_purchase_quantity='2.5' and calculation_snapshot->>'base_quantity'=base_quantity from public.execution_estimate_lines where id=line),'persisted service quantity matches canonical calculation');
 perform pg_temp.execution_assert((select unit_cost='100.25' and estimated_cost='250.63' and rate_snapshot->>'source_reference'='Internal labour schedule' from public.execution_estimate_line_costs where line_id=line),'service cost uses exact contract precision and source snapshot');
 perform pg_temp.execution_assert((select not(calculation_snapshot ? 'unit_cost') and not(calculation_snapshot ? 'rate_snapshot') from public.execution_estimate_lines where id=line),'quantity snapshot excludes internal cost fields');
 perform pg_temp.execution_denied(format('select public.execution_line_save(%L,%L,%L)',org,revision,payload),'stale line save rejected');
 perform pg_temp.execution_denied(format('select public.execution_line_save(%L,%L,%L)',org,revision,payload||jsonb_build_object('version',2,'override_quantity','3')),'override without reason rejected');
 for s in select id from public.execution_estimate_scope_items where revision_id=revision and coverage='unestimated' loop
 select version into v from public.execution_estimate_revisions where id=revision;
 perform public.execution_estimate_command(org,'exclude_scope',jsonb_build_object('id',revision,'version',v,'scope_id',s,'reason','Separate execution package'));
 end loop;
 select version into v from public.execution_estimate_revisions where id=revision;
 perform public.execution_estimate_command(org,'submit',jsonb_build_object('id',revision,'version',v));
 perform pg_temp.execution_assert((select status='under_review' and version=v+1 from public.execution_estimate_revisions where id=revision),'submission transitions and increments version atomically');
 perform public.execution_estimate_command(org,'approve',jsonb_build_object('id',revision,'version',v+1));
 perform pg_temp.execution_assert((select status='approved' and version=v+2 from public.execution_estimate_revisions where id=revision),'approval transitions and increments version atomically');
 pr_input=jsonb_build_object('idempotency_key',gen_random_uuid(),'revision_id',revision,'delivery_location','Project site','sources',jsonb_build_array(jsonb_build_object('line_id',line,'quantity','2.5')));
 pr=public.execution_requisition_create(org,pr_input);
 perform pg_temp.execution_assert(pr=public.execution_requisition_create(org,pr_input),'requisition retry is idempotent');
 perform pg_temp.execution_assert((select quantity='2.5' and estimate_line_id=line from public.purchase_requisition_sources where requisition_id=pr),'requisition retains exact estimate source allocation');
 perform pg_temp.execution_denied(format('select public.execution_requisition_create(%L,%L)',org,pr_input||jsonb_build_object('notes','changed')),'requisition retry payload mismatch rejected');
 perform pg_temp.execution_denied(format('select public.execution_requisition_create(%L,%L)',org,pr_input||jsonb_build_object('idempotency_key',gen_random_uuid())),'second requisition cannot exceed approved demand');
 perform public.execution_requisition_transition(org,pr,1,'submit');
 perform public.execution_requisition_transition(org,pr,2,'approve');
 perform pg_temp.execution_assert((select status='approved' and version=3 from public.purchase_requisitions where id=pr),'requisition submission and approval preserve state');
 vendor=public.execution_configure(org,'vendors','{"name":"Test supplier","code":"TEST-SUPPLIER"}');
 rfq_input=jsonb_build_object('requisition_id',pr,'idempotency_key',gen_random_uuid(),'vendor_ids',jsonb_build_array(vendor),'items',jsonb_build_array(jsonb_build_object('requisition_item_id',(select id from public.purchase_requisition_items where requisition_id=pr),'quantity','2.5')));
 rfq=public.execution_rfq_create(org,rfq_input);
 perform pg_temp.execution_assert(rfq=public.execution_rfq_create(org,rfq_input),'RFQ retry is idempotent');
 perform public.execution_rfq_transition(org,rfq,1,'issue');
 perform pg_temp.execution_assert((select status='issued' and document_snapshot#>>'{items,0,quantity}'='2.5' and not(document_snapshot::text like '%250.63%') from public.rfqs where id=rfq),'issued RFQ freezes requested quantities without estimated costs');
 perform public.execution_configure(org,'vendors',jsonb_build_object('id',vendor,'version',1,'name','Renamed supplier'));
 perform pg_temp.execution_assert((select vendor_snapshot->>'name'='Test supplier' from public.rfq_vendors where rfq_id=rfq),'RFQ recipient snapshot survives master changes');
 perform pg_temp.execution_assert((select sum(quantity::numeric)=2.5 from public.purchase_requisition_sources where requisition_id=pr),'RFQ does not multiply approved procurement demand');
 quote_input=jsonb_build_object('idempotency_key',gen_random_uuid(),'rfq_id',rfq,'vendor_id',vendor,'reference','SUP-001','currency','INR','valid_until',current_date+30,'freight','10','items',jsonb_build_array(jsonb_build_object('rfq_item_id',(select id from public.rfq_items where rfq_id=rfq),'quantity','2.5','unit_price','100','discount','25','tax_mode','exclusive','tax_components',jsonb_build_array(jsonb_build_object('name','Tax','rate','18')))));
 quote=public.execution_vendor_quote_save(org,quote_input);
 perform pg_temp.execution_assert(quote=public.execution_vendor_quote_save(org,quote_input),'vendor quote retry is idempotent');
 perform pg_temp.execution_assert((select subtotal='225' and tax_amount='40.5' and total='275.5' from public.vendor_quotes where id=quote),'quote discount, tax and freight use exact arithmetic');
 perform public.execution_vendor_quote_transition(org,quote,1,'record');
 perform pg_temp.execution_assert((public.execution_vendor_comparison(org,rfq)#>>'{vendors,0,quotes,0,total}')='275.5','vendor comparison presents recorded quote facts');
 perform pg_temp.execution_denied(format('select public.execution_vendor_quote_save(%L,%L)',org,quote_input||jsonb_build_object('id',quote,'version',2)),'recorded vendor quote cannot be rewritten');
 select id into quote_item from public.vendor_quote_items where quote_id=quote;
 po_input=jsonb_build_object('quote_id',quote,'idempotency_key',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('quote_item_id',quote_item,'quantity','1')));
 po1=public.execution_po_create(org,po_input);
 perform pg_temp.execution_assert(po1=public.execution_po_create(org,po_input),'purchase order creation retry is idempotent');
 po2=public.execution_po_create(org,po_input||jsonb_build_object('idempotency_key',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('quote_item_id',quote_item,'quantity','1.5'))));
 competing_po=public.execution_po_create(org,po_input||jsonb_build_object('idempotency_key',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('quote_item_id',quote_item,'quantity','2.5'))));
 perform public.execution_po_transition(org,po1,1,'issue');
 perform public.execution_po_transition(org,po2,1,'issue');
 perform pg_temp.execution_assert((select sum(total::numeric)=275.5 from public.purchase_order_costs where po_id in (po1,po2)),'split awards allocate exact quote total including freight');
 perform pg_temp.execution_denied(format('select public.execution_po_transition(%L,%L,1,''issue'')',org,competing_po),'issue rechecks remaining demand against competing drafts');
 perform pg_temp.execution_assert((select status='draft' from public.purchase_orders where id=competing_po),'failed issue leaves competing draft unchanged');
 select id into po_item from public.purchase_order_items where po_id=po1;
 receipt_input=jsonb_build_object('po_id',po1,'idempotency_key',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('po_item_id',po_item,'received_quantity','0.5','accepted_quantity','0.4','rejected_quantity','0.1','notes','Service portion requires rework')));
 receipt=public.execution_receipt_record(org,receipt_input);
 perform pg_temp.execution_assert(receipt=public.execution_receipt_record(org,receipt_input),'receipt retry is idempotent');
 perform pg_temp.execution_assert((select status='partially_received' and version=3 from public.purchase_orders where id=po1),'partial service receipt updates PO lifecycle');
 perform pg_temp.execution_denied(format('select public.execution_receipt_record(%L,%L)',org,receipt_input||jsonb_build_object('idempotency_key',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('po_item_id',po_item,'received_quantity','0.6','accepted_quantity','0.6','rejected_quantity','0')))),'receipt cannot exceed remaining ordered quantity');
 report=public.execution_cost_report(org,(select project_id from public.contracts where id=contract));
 perform pg_temp.execution_assert((select x->>'committed_cost'='275.5' and x->>'accepted_received_cost'='44.08' from jsonb_array_elements(report->'contracts')x where x->>'contract_id'=contract::text),'cost report separates commitments from accepted receipts');
 perform public.execution_receipt_record(org,receipt_input||jsonb_build_object('idempotency_key',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('po_item_id',po_item,'received_quantity','0.5','accepted_quantity','0.5','rejected_quantity','0'))));
 perform pg_temp.execution_assert((select status='received' from public.purchase_orders where id=po1),'full received quantity completes PO even with documented rejection');
 perform pg_temp.execution_denied(format('select public.execution_po_transition(%L,%L,4,''cancel'',''Cannot undo receipt'')',org,po1),'received PO cannot be cancelled');
 perform pg_temp.execution_assert((public.execution_search(org,'purchase_orders',jsonb_build_object('project_id',(select project_id from public.contracts where id=contract),'contract_id',contract))->>'total')::integer=3,'execution search filters tenant project and contract with bounded results');
 perform pg_temp.execution_assert((public.execution_search(org,'vendors','{"query":"Renamed"}')->>'total')::integer=1,'execution text search uses configured vendor name');
 perform pg_temp.execution_assert(public.execution_detail(org,'purchase_orders',po1)->>'status'='received','execution detail returns authorized quantity record');
 perform pg_temp.execution_assert(public.execution_document(org,'purchase_orders',po1)->>'total'='110.2','purchase order document uses frozen cost snapshot');
 perform pg_temp.execution_assert(public.execution_document(org,'rfqs',rfq,vendor)#>>'{vendor,name}'='Test supplier','RFQ document projects only selected frozen recipient');
 perform pg_temp.execution_denied(format('select public.execution_requisition_transition(%L,%L,3,''cancel'',''Cancel with active RFQ'')',org,pr),'active RFQ prevents requisition cancellation');
 successor=public.execution_estimate_command(org,'revise',jsonb_build_object('id',revision,'version',v+2));
 perform pg_temp.execution_assert(successor<>revision and (select status='approved' from public.execution_estimate_revisions where id=revision),'new revision preserves approved predecessor');
 perform pg_temp.execution_assert((select count(*) from public.execution_estimate_scope_items where revision_id=successor)=(select count(*) from public.execution_estimate_scope_items where revision_id=revision),'revision copies source scope history');
 perform pg_temp.execution_assert((select count(*) from public.execution_estimate_line_costs where revision_id=successor)=1 and (select estimated_cost='250.63' from public.execution_estimate_line_costs where revision_id=successor),'revision preserves estimated cost snapshot');
 perform public.execution_recipe_apply(org,successor,jsonb_build_object('version',1,'scope_id',(select id from public.execution_estimate_scope_items where revision_id=successor order by id limit 1),'recipe_id',(select id from public.estimation_recipes where name='Wardrobe recipe'),'recipe_reason','Manual recipe choice','measurements',jsonb_build_object('finished_area','80'),'measurement_note','Verified drawing area'));
 perform pg_temp.execution_assert((select planned_purchase_quantity='6' and base_quantity='160' from public.execution_estimate_lines where revision_id=successor and cost_kind='material'),'whole recipe application uses explicit conversion and default waste');
 perform public.execution_line_remove(org,successor,(select id from public.execution_estimate_lines where revision_id=successor and cost_kind='material'),2);
 perform pg_temp.execution_assert((select count(*)=1 from public.execution_estimate_lines where revision_id=successor),'draft recipe line removal preserves other requirements');
 perform public.execution_line_save(org,successor,(payload-'manual_cost')||jsonb_build_object('id',(select id from public.execution_estimate_lines where revision_id=successor),'scope_id',(select scope_id from public.execution_estimate_lines where revision_id=successor),'version',3,'notes','Quantity review retains planning rate'));
 perform pg_temp.execution_assert((select unit_cost='100.25' and estimated_cost='250.63' and rate_snapshot->>'source_reference'='Internal labour schedule' from public.execution_estimate_line_costs where revision_id=successor),'draft edit retains historical rate when no replacement is requested');
 perform pg_temp.execution_assert(public.execution_document(org,'execution_estimate_revisions',revision)->>'kind'='execution_estimate','approved estimate has protected historical document');
 perform pg_temp.execution_assert((public.execution_estimate_demand(org,revision)#>>'{items,0,remaining}')='0','approved requisition reserves source demand in UI projection');
 perform pg_temp.execution_assert((public.execution_po_progress(org,po1)#>>'{items,0,remaining}')='0','receipt projection shows remaining ordered quantity');
 perform pg_temp.execution_assert((select (x#>>'{commercial,current_value}')='1000' and (x#>>'{commercial,estimated_contribution}')='749.37' from jsonb_array_elements(public.execution_cost_dashboard(org,(select project_id from public.contracts where id=contract))->'contracts')x where x->>'contract_id'=contract::text),'cost dashboard labels commercial value and estimated contribution');
 perform pg_temp.execution_denied(format('select public.execution_line_save(%L,%L,%L)',org,revision,payload||jsonb_build_object('version',v+2)),'approved estimate rejects line edits');
 perform pg_temp.execution_denied(format('select public.execution_estimate_command(%L,''sync'',%L)',org,jsonb_build_object('id',successor,'version',999)),'stale estimate version rejected');
 perform pg_temp.execution_denied(format('update public.execution_estimate_revisions set notes=''rewrite'' where id=%L',revision),'direct authenticated mutation denied');
end$$;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';revision uuid;scope uuid;rate public.material_cost_revisions;before_doc jsonb;begin
 select r.id into revision from public.execution_estimate_revisions r join public.contracts c on c.id=r.contract_id join public.quotation_revisions qr on qr.id=c.revision_id join public.quotations q on q.id=qr.quotation_id where q.quotation_number='EXECUTION-TEST' and r.status='draft';
 select id into scope from public.execution_estimate_scope_items where revision_id=revision order by id limit 1;
 perform public.execution_recipe_apply(org,revision,jsonb_build_object('version',4,'scope_id',scope,'recipe_id',(select id from public.estimation_recipes where name='Wardrobe recipe'),'recipe_reason','Snapshot regression','measurements',jsonb_build_object('finished_area','80'),'measurement_note','Verified area'));
 perform public.execution_estimate_command(org,'submit',jsonb_build_object('id',revision,'version',5));
 perform public.execution_estimate_command(org,'approve',jsonb_build_object('id',revision,'version',6));
 before_doc=public.execution_document(org,'execution_estimate_revisions',revision);
 select * into rate from public.material_cost_revisions where source_reference='Test planning rate';
 perform public.execution_cost_record(org,jsonb_build_object('variant_id',rate.variant_id,'currency','INR','unit_cost','3000','source_reference','Replacement planning rate','valid_from',current_date+1,'replaces_id',rate.id,'version',rate.version));
 perform pg_temp.execution_assert(before_doc=public.execution_document(org,'execution_estimate_revisions',revision),'approved estimate document is unchanged after material rate replacement');
end$$;
reset role;
insert into public.organization_entitlements(organization_id,module_id,enabled,source) select 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',id,false,'manual' from public.modules where key='billing';
set local role authenticated;
select pg_temp.execution_assert((select count(*)>0 from public.execution_estimate_revisions),'execution remains visible without Billing entitlement');
select pg_temp.execution_assert((select (public.execution_scope(organization_id,contract_id)->>'total')::integer>0 from public.execution_estimates limit 1),'commercial scope projection does not require Billing entitlement');
reset role;
insert into public.membership_roles(organization_id,membership_id,role_id) select m.organization_id,m.id,r.id from public.organization_memberships m join public.roles r on r.organization_id=m.organization_id where m.organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and m.user_id='22222222-2222-4222-8222-222222222222' and r.key='site_supervisor' on conflict do nothing;
set local request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';
set local role authenticated;
select pg_temp.execution_assert((select count(*)>0 from public.execution_estimate_lines),'Site can view execution quantities');
select pg_temp.execution_assert((select count(*)=0 from public.execution_estimate_line_costs),'Site cannot read execution cost rows');
select pg_temp.execution_assert((select count(*)=0 from public.material_cost_revisions),'Site cannot read material rates');
select pg_temp.execution_assert((select count(*)>0 from public.purchase_order_items),'Site can read ordered quantities');
select pg_temp.execution_assert((select count(*)=0 from public.purchase_order_item_costs),'Site cannot read per-item purchase prices');
select pg_temp.execution_assert((select count(*)>0 from public.goods_receipts),'Site can read receipt records');
select pg_temp.execution_denied('select public.execution_search(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''purchase_order_costs'')','Site cannot query internal cost search');
select pg_temp.execution_denied('select public.execution_document(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''purchase_orders'',gen_random_uuid())','Site cannot access priced PO document endpoint');
select pg_temp.execution_denied('select public.execution_document(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''execution_estimate_revisions'',gen_random_uuid())','Site cannot access internal estimate document endpoint');
select pg_temp.execution_assert((select count(*)=0 from public.execution_estimate_documents),'Site cannot directly read historical internal estimate PDFs');
select pg_temp.execution_denied('select public.execution_cost_record(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''{}'')','Site cannot create material costs');
reset role;
delete from public.membership_roles where membership_id in (select id from public.organization_memberships where organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and user_id='22222222-2222-4222-8222-222222222222');
insert into public.membership_roles(organization_id,membership_id,role_id) select m.organization_id,m.id,r.id from public.organization_memberships m join public.roles r on r.organization_id=m.organization_id where m.organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and m.user_id='22222222-2222-4222-8222-222222222222' and r.key='interior_designer';
set local role authenticated;
select pg_temp.execution_assert((select count(*)=0 from public.material_cost_revisions),'Designer cannot read material rates');
select pg_temp.execution_assert((select count(*)=0 from public.vendor_quote_items),'Designer cannot read vendor rates');
select pg_temp.execution_assert((select count(*)=0 from public.purchase_order_costs),'Designer cannot read procurement costs');
select pg_temp.execution_denied('select public.execution_document(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''execution_estimate_revisions'',gen_random_uuid())','Designer cannot download internal estimates');
reset role;
delete from public.membership_roles where membership_id in (select id from public.organization_memberships where organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and user_id='22222222-2222-4222-8222-222222222222');
insert into public.membership_roles(organization_id,membership_id,role_id) select m.organization_id,m.id,r.id from public.organization_memberships m join public.roles r on r.organization_id=m.organization_id where m.organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and m.user_id='22222222-2222-4222-8222-222222222222' and r.key='sales';
set local role authenticated;
select pg_temp.execution_assert((select count(*)=0 from public.material_cost_revisions),'Sales cannot read material rates');
select pg_temp.execution_assert((select count(*)=0 from public.vendor_quote_items),'Sales cannot read vendor rates');
select pg_temp.execution_assert((select count(*)=0 from public.purchase_order_costs),'Sales cannot read procurement costs');
select pg_temp.execution_denied('select public.execution_document(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''execution_estimate_revisions'',gen_random_uuid())','Sales cannot download internal estimates');
reset role;
select pg_temp.execution_denied('update public.goods_receipt_items set accepted_quantity=''0''','receipt lines remain append-only even for privileged writers');
select pg_temp.execution_denied('update public.purchase_order_item_costs set unit_price=''1'' where po_id in (select id from public.purchase_orders where status=''received'')','issued purchase costs remain frozen even for privileged writers');
insert into auth.users(id,email,raw_user_meta_data) values('60000000-0000-4000-8000-000000000001','execution.other@example.test','{}');
set local request.jwt.claim.sub='60000000-0000-4000-8000-000000000001';
select public.create_organization('{"name":"Execution other tenant","slug":"execution-other-test","currency":"INR","country":"IN","timezone":"Asia/Kolkata"}');
set local role authenticated;
select pg_temp.execution_assert((select count(*)=0 from public.execution_estimate_lines),'other tenant cannot read execution quantities');
select pg_temp.execution_assert((select count(*)=0 from public.purchase_requisitions),'other tenant cannot read requisitions');
select pg_temp.execution_denied('select public.execution_estimate_command(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''create'',''{}'')','other tenant cannot create estimate');
reset role;
rollback;




