begin;
create function pg_temp.fin_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end$$;
create function pg_temp.fin_denied(statement text,label text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege or check_violation or invalid_parameter_value or foreign_key_violation or serialization_failure or unique_violation or not_null_violation then raise notice 'PASS: %',label;return;end;raise exception 'FAIL: %',label;end$$;
create function pg_temp.fin_change(payload jsonb) returns uuid language plpgsql as $$declare msg text;key text;begin
 select secret_hex into key from private.quotation_signing_keys where singleton;
 msg=(payload||jsonb_build_object('operation','finance_change','actor',auth.uid(),'organization_id','dddddddd-dddd-4ddd-8ddd-dddddddddddd','nonce',gen_random_uuid(),'expires',floor(extract(epoch from now()))+90))::text;
 return public.change_order_command(msg,encode(extensions.hmac(convert_to(msg,'UTF8'),decode(key,'hex'),'sha256'),'hex'));
end$$;
-- Fixture uses frozen quotation content and the real Phase 4 approval RPC.
set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
insert into private.quotation_signing_keys(singleton,secret_hex) values(true,repeat('a',64)) on conflict(singleton) do nothing;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';customer uuid;project uuid;root uuid=gen_random_uuid();revision uuid=gen_random_uuid();share jsonb;snapshot jsonb;begin
 select id,customer_id into project,customer from public.projects where organization_id=org order by id limit 1;
 snapshot=jsonb_build_object('snapshot_version',1,'name','Original wardrobe','line_type','manual','quantity','1','unit',jsonb_build_object('key','each','label','Each'),'display_rate','1000','effective_amount','1000','final_amount','1000','discount_amount','0','minimum_amount',null,'customer_specifications','[]'::jsonb);
 insert into public.quotations(id,organization_id,customer_id,project_id,quotation_number) values(root,org,customer,project,'FINANCE-TEST');
 insert into public.quotation_revisions(id,organization_id,quotation_id,project_id,revision_number,currency,valid_until,document_snapshot) select revision,org,root,project,1,'INR',current_date+30,jsonb_build_object('branding',branding,'customer',jsonb_build_object('name','Finance Customer','billing_address','{}'::jsonb),'project',jsonb_build_object('name','Finance Project','site_address','{}'::jsonb),'display',jsonb_build_object('quantity',true,'unit_rate',true,'specifications',true)) from public.organization_quotation_settings where organization_id=org;
 insert into public.quotation_items(organization_id,revision_id,project_id,snapshot) values(org,revision,project,snapshot);
 update public.quotation_revisions set status='issued',issued_at=now(),totals=private.quotation_totals(id,discount) where id=revision;
 update public.quotations set status='issued',current_revision_id=revision where id=root;
 share=public.quotation_share_manage(org,'create',jsonb_build_object('revision_id',revision));
 perform public.public_quotation(share->>'token','respond','{"action":"approved","name":"Finance Customer","acknowledged":true}');
end$$;
set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';revision uuid;contract uuid;schedule uuid;milestone uuid;request uuid;invoice uuid;payment uuid;method uuid;key uuid=gen_random_uuid();input jsonb;data jsonb;tax uuid;receipt uuid;before_doc jsonb;allocation uuid;t text;begin
 select r.id into revision from public.quotation_revisions r join public.quotations q on q.id=r.quotation_id where q.quotation_number='FINANCE-TEST';
 contract=public.contract_create(org,revision);
 perform pg_temp.fin_assert(contract=public.contract_create(org,revision),'idempotent accepted handoff');
 perform pg_temp.fin_assert((select original_contract_value='1000' and contract_number like 'CT-%' from public.contracts where id=contract),'exact accepted value and contract numbering');
 perform pg_temp.fin_denied(format('select public.contract_create(%L,%L)',org,gen_random_uuid()),'unaccepted revision rejected');
 perform public.contract_transition(org,contract,1,'active');
 schedule=public.payment_schedule_save(org,contract,'{"label":"Initial milestones","items":[{"label":"Booking","calculation_type":"percentage","value":"10"},{"label":"Production","calculation_type":"fixed","value":"400"},{"label":"Handover","calculation_type":"remaining","value":"0"}]}');
 perform pg_temp.fin_assert((select sum(expected_amount::numeric)=1000 from public.payment_schedule_items where schedule_id=schedule),'mixed schedule exact total');
 perform pg_temp.fin_assert((select expected_amount='500' from public.payment_schedule_items where schedule_id=schedule and label='Handover'),'remaining balance exact');
 perform pg_temp.fin_denied(format('select public.payment_schedule_save(%L,%L,%L)',org,contract,'{"label":"Bad","items":[{"label":"Bad","calculation_type":"percentage","value":"101"}]}'),'percentage over-allocation rejected');
 perform public.payment_schedule_activate(org,schedule,1);
 perform pg_temp.fin_assert(schedule=public.payment_schedule_activate(org,schedule,1),'activation idempotent');
 perform pg_temp.fin_denied(format('select public.payment_schedule_save(%L,%L,%L)',org,contract,jsonb_build_object('id',schedule,'version',2,'label','Rewrite','items',jsonb_build_array(jsonb_build_object('label','Rewrite','calculation_type','fixed','value','1')))),'active schedule frozen');
 select id into milestone from public.payment_schedule_items where schedule_id=schedule and label='Booking';
 request=public.payment_request_issue(org,milestone,current_date-1,'Booking due');
 perform pg_temp.fin_assert(request=public.payment_request_issue(org,milestone),'payment request duplicate protection');
 perform pg_temp.fin_assert(public.finance_detail(org,'payment_requests',request)->>'effective_status'='overdue','server-derived overdue request');
 input=jsonb_build_object('invoice_type','tax_invoice','issue_date',current_date-2,'due_date',current_date-1,'tax_mode','exclusive','tax_application','line','items',jsonb_build_array(jsonb_build_object('description','Booking','quantity','999','unit_rate','999','source_type','milestone','source_id',milestone)));
 invoice=public.invoice_save(org,contract,input);
 perform pg_temp.fin_assert((select total='100' from public.invoices where id=invoice),'milestone price is server-derived');
 perform public.invoice_issue(org,invoice,1);
 perform pg_temp.fin_assert(invoice=public.invoice_issue(org,invoice,1),'invoice issue idempotent');
 perform pg_temp.fin_assert(public.finance_detail(org,'invoices',invoice)->>'effective_status'='overdue','server-derived overdue invoice');
 before_doc=public.finance_document(org,'invoices',invoice);
 perform pg_temp.fin_denied(format('select public.invoice_save(%L,%L,%L)',org,contract,input||jsonb_build_object('id',invoice,'version',2)),'issued invoice edit rejected');
 select id into method from public.payment_methods where organization_id=org and kind='bank_transfer' limit 1;
 input=jsonb_build_object('idempotency_key',key,'payment_date',current_date,'amount','40','method_id',method,'allocations',jsonb_build_array(jsonb_build_object('invoice_id',invoice,'amount','40','idempotency_key',gen_random_uuid())));
 payment=public.payment_record(org,contract,input);
 perform pg_temp.fin_assert(payment=public.payment_record(org,contract,input),'payment retry idempotent');
 perform pg_temp.fin_denied(format('select public.payment_record(%L,%L,%L)',org,contract,input||'{"amount":"41"}'::jsonb),'payment retry mismatch rejected');
 perform pg_temp.fin_assert(public.finance_detail(org,'invoices',invoice)->>'effective_status'='partially_paid','partial payment status');
 select id into receipt from public.receipts where payment_id=payment;
 perform pg_temp.fin_assert(public.finance_document(org,'receipts',receipt)->>'total'='40','receipt matches actual payment');
 perform pg_temp.fin_denied(format('select public.invoice_void(%L,%L,''Incorrect'')',org,invoice),'allocated invoice cannot be voided');
 perform pg_temp.fin_denied(format('select public.payment_allocate(%L,%L,%L)',org,payment,jsonb_build_object('invoice_id',invoice,'amount','1','idempotency_key',gen_random_uuid())),'payment over-allocation rejected');
 perform public.payment_void(org,payment,'Duplicate transfer entry');
 perform pg_temp.fin_assert((select status='void' from public.receipts where id=receipt),'receipt void retained');
 perform pg_temp.fin_assert((select count(*)=1 from public.payment_allocations where payment_id=payment and reversed_at is not null),'allocation reversal retained');
 perform pg_temp.fin_assert(public.finance_detail(org,'invoices',invoice)->>'balance'='100','void restores invoice balance');
 payment=public.payment_record(org,contract,jsonb_build_object('idempotency_key',gen_random_uuid(),'payment_date',current_date,'amount','150','method_id',method,'allocations',jsonb_build_array(jsonb_build_object('invoice_id',invoice,'amount','100','idempotency_key',gen_random_uuid()))));
 perform pg_temp.fin_assert(public.finance_detail(org,'invoices',invoice)->>'effective_status'='paid','fully paid invoice');
 perform pg_temp.fin_assert(public.finance_detail(org,'payments',payment)->>'unallocated_amount'='50','advance credit retained');
 perform pg_temp.fin_assert(public.finance_detail(org,'payment_schedule_items',milestone)->>'effective_status'='settled','milestone settled only from actual allocations');
 perform pg_temp.fin_assert(public.finance_summary(org,contract)->0->>'unallocated_advance'='50','summary advance distinct from invoice balance');
 perform pg_temp.fin_assert(public.finance_summary(org,contract)->0->>'unbilled_contract_value'='900','unbilled contract balance exact');
 perform pg_temp.fin_assert(public.finance_document(org,'invoices',invoice)=before_doc,'payments never alter issued invoice PDF snapshot');
 perform pg_temp.fin_denied(format('select public.contract_transition(%L,%L,2,''cancelled'',''Cancelled job'')',org,contract),'financial history blocks cancellation');
 perform pg_temp.fin_denied(format('select public.payment_allocate(%L,%L,%L)',org,payment,jsonb_build_object('invoice_id',invoice,'amount','1','idempotency_key',gen_random_uuid())),'invoice overpayment rejected');
 foreach t in array array['contracts','payment_schedules','payment_schedule_items','payment_requests','invoices','invoice_items','payments','payment_allocations','receipts','change_orders','change_order_items','organization_billing_settings','payment_methods','tax_codes'] loop
 perform pg_temp.fin_denied(format('delete from public.%I where organization_id=%L',t,org),'direct financial DML denied: '||t);
 end loop;
end$$;
reset role;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';c uuid;original uuid;co uuid;data jsonb;begin
 select c0.id into c from public.contracts c0 join public.quotations q on q.current_revision_id=c0.revision_id where q.quotation_number='FINANCE-TEST';
 select i.id into original from public.quotation_items i join public.contracts c0 on c0.revision_id=i.revision_id where c0.id=c;
 data=jsonb_build_object('action','save','contract_id',c,'reason','Customer requested upgrade','items',jsonb_build_array(jsonb_build_object('change_type','modification','description','PU wardrobe','reason','Customer finish change','pricing_type','manual','original_item_id',original,'quantity','1','unit_rate','1200')));
 co=pg_temp.fin_change(data);
 perform pg_temp.fin_assert((select net_adjustment='200' from public.change_orders where id=co),'modification stores original versus new delta');
 perform pg_temp.fin_assert(private.contract_value(c)=1000,'draft change does not change contract');
 perform pg_temp.fin_change(jsonb_build_object('action','issue','contract_id',c,'id',co,'version',1));
 perform pg_temp.fin_assert(private.contract_value(c)=1000,'issued change does not change contract');
 perform pg_temp.fin_change(jsonb_build_object('action','approve','contract_id',c,'id',co,'version',2,'evidence','Customer signed printed change order'));
 perform pg_temp.fin_change(jsonb_build_object('action','approve','contract_id',c,'id',co,'version',2,'evidence','Customer signed printed change order'));
 perform pg_temp.fin_assert(private.contract_value(c)=1200,'approved change updates contract once');
 perform pg_temp.fin_assert((select original_contract_value='1000' from public.contracts where id=c),'original contract unchanged');
 perform pg_temp.fin_assert((select sum(expected_amount::numeric)=1000 from public.payment_schedule_items where contract_id=c),'historical payment schedule unchanged');
 perform pg_temp.fin_assert(public.finance_summary(org,c)->0->>'schedule_unallocated'='200','new schedule gap visible');
 perform pg_temp.fin_denied(format('update public.change_orders set net_adjustment=''300'' where id=%L',co),'approved change immutable under privileged write');
 perform pg_temp.fin_denied(format('update public.invoices set total=''3'' where contract_id=%L and status=''issued''',c),'issued invoice immutable under privileged write');
 perform pg_temp.fin_denied(format('update public.contracts set original_contract_value=''3'' where id=%L',c),'contract baseline immutable under privileged write');
 perform pg_temp.fin_denied(format('select pg_temp.fin_change(%L)',data),'original scope cannot be changed twice');
 co=pg_temp.fin_change(jsonb_build_object('action','save','contract_id',c,'reason','Goodwill deduction','items',jsonb_build_array(jsonb_build_object('change_type','price_adjustment','description','Goodwill','reason','Customer agreement','pricing_type','manual','adjustment','-50'))));
 perform pg_temp.fin_change(jsonb_build_object('action','issue','contract_id',c,'id',co,'version',1));
 perform pg_temp.fin_change(jsonb_build_object('action','approve','contract_id',c,'id',co,'version',2,'evidence','Agreed deduction'));
 perform pg_temp.fin_assert(private.contract_value(c)=1150,'negative adjustment exact');
 perform pg_temp.fin_assert(private.finance_tax(118,'[{"name":"CGST","rate":"9"},{"name":"SGST","rate":"9"}]','inclusive',2)->>'tax'='18','inclusive component tax exact');
 perform pg_temp.fin_assert(private.finance_tax(100,'[{"name":"CGST","rate":"9"},{"name":"SGST","rate":"9"}]','exclusive',2)->>'total'='118','exclusive component tax exact');
 perform pg_temp.fin_assert(private.finance_tax(0.05,'[{"name":"A","rate":"10"},{"name":"B","rate":"10"}]','exclusive',2)->>'tax'='0.02','tax components round half up individually');
 perform pg_temp.fin_assert((select bool_and(relrowsecurity and relforcerowsecurity) from pg_class where oid in ('public.contracts'::regclass,'public.invoices'::regclass,'public.payments'::regclass,'public.payment_allocations'::regclass,'public.change_orders'::regclass)),'finance RLS enabled and forced');
end$$;
set local request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';
set local role authenticated;
do $$declare t text;n integer;org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';begin
 foreach t in array array['contracts','invoices','payments','payment_allocations','change_orders','receipts','organization_billing_settings'] loop
 execute format('select count(*) from public.%I where organization_id=$1',t) into n using org;perform pg_temp.fin_assert(n=0,'financial rows hidden from Sales: '||t);
 perform pg_temp.fin_denied(format('select public.finance_search(%L,%L)',org,t),'financial API denied to Sales: '||t);end loop;
 perform pg_temp.fin_denied(format('select public.payment_record(%L,%L,''{}'')',org,gen_random_uuid()),'unauthorized payment recording denied');
 perform pg_temp.fin_denied(format('select public.invoice_issue(%L,%L,1)',org,gen_random_uuid()),'unauthorized invoice issue denied');
 perform pg_temp.fin_denied(format('select public.finance_summary(%L)',org),'unauthorized finance summary denied');
end$$;
reset role;
insert into public.membership_roles(organization_id,membership_id,role_id) select m.organization_id,m.id,r.id from public.organization_memberships m join public.roles r on r.organization_id=m.organization_id where m.organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and m.user_id='22222222-2222-4222-8222-222222222222' and r.key='accountant';
set local role authenticated;
select pg_temp.fin_assert((public.finance_search('dddddddd-dddd-4ddd-8ddd-dddddddddddd','invoices')->>'total')::integer>0,'Accountant can read invoices');
select pg_temp.fin_assert(private.finance_access('dddddddd-dddd-4ddd-8ddd-dddddddddddd','payment.record'),'Accountant can record offline payments');
select pg_temp.fin_denied('select public.finance_search(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''change_orders'')','Accountant cannot read change orders without separate grant');
reset role;
update public.membership_roles mr set branch_id=(select id from public.branches where organization_id=mr.organization_id order by id limit 1) from public.roles r,public.organization_memberships m where mr.role_id=r.id and mr.membership_id=m.id and r.key='accountant' and m.user_id='22222222-2222-4222-8222-222222222222' and mr.organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
set local role authenticated;
select pg_temp.fin_denied('select public.finance_search(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''invoices'')','branch-only Accountant grant cannot read organization finance');
reset role;
delete from public.membership_roles mr using public.roles r,public.organization_memberships m where mr.role_id=r.id and mr.membership_id=m.id and r.key='accountant' and m.user_id='22222222-2222-4222-8222-222222222222' and mr.organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';c public.contracts;invoice uuid;second uuid;proforma uuid;payment uuid;method uuid;tax uuid;input jsonb;before_doc jsonb;settings public.organization_billing_settings;schedule uuid;co uuid;original uuid;fresh uuid;begin
 select c0.* into c from public.contracts c0 join public.quotations q on q.current_revision_id=c0.revision_id where q.quotation_number='FINANCE-TEST';
 perform set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
 select id into method from public.payment_methods where organization_id=org and kind='bank_transfer' limit 1;
 select id into tax from public.tax_codes where organization_id=org and code='DEMO-INTRA-18';
 input=jsonb_build_object('invoice_type','proforma','issue_date',current_date,'due_date',current_date+5,'tax_mode','inclusive','tax_application','document','tax_code_id',tax,'items',jsonb_build_array(jsonb_build_object('description','Tax fixture','quantity','1','unit','each','unit_rate','118','source_type','manual')));
 proforma=public.invoice_save(org,c.id,input);perform public.invoice_issue(org,proforma,1);
 perform pg_temp.fin_assert((select total='118' and tax_amount='18' and taxable_amount='100' from public.invoices where id=proforma),'invoice document tax matches components');
 perform pg_temp.fin_assert(public.finance_summary(org,c.id)->0->>'invoiced_amount'='100','proforma excluded from invoiced amount');
 payment=public.payment_record(org,c.id,jsonb_build_object('idempotency_key',gen_random_uuid(),'payment_date',current_date,'amount','120','method_id',method));
 perform pg_temp.fin_denied(format('select public.payment_allocate(%L,%L,%L)',org,payment,jsonb_build_object('invoice_id',proforma,'amount','118','idempotency_key',gen_random_uuid())),'proforma cannot receive invoice allocations');
 invoice=public.invoice_save(org,c.id,input||jsonb_build_object('invoice_type','tax_invoice'));perform public.invoice_issue(org,invoice,1);
 before_doc=public.finance_document(org,'invoices',invoice);
 select * into settings from public.organization_billing_settings where organization_id=org;
 perform public.finance_configure(org,'organization_billing_settings',jsonb_build_object('id',settings.id,'version',settings.version,'legal_name','Changed legal name','payment_instructions','Changed bank details'));
 perform public.finance_configure(org,'tax_codes',jsonb_build_object('id',tax,'version',1,'components',jsonb_build_array(jsonb_build_object('name','Changed tax','rate','20'))));
 perform pg_temp.fin_assert(public.finance_document(org,'invoices',invoice)=before_doc,'issued PDF survives billing and tax configuration changes');
 input=input||jsonb_build_object('invoice_type','tax_invoice','tax_code_id',null,'tax_application','line','items',jsonb_build_array(jsonb_build_object('description','Second invoice','quantity','1','unit','each','unit_rate','2','source_type','manual')));
 second=public.invoice_save(org,c.id,input);perform public.invoice_issue(org,second,1);
 perform public.payment_allocate(org,payment,jsonb_build_object('invoice_id',invoice,'amount','118','idempotency_key',gen_random_uuid()));
 perform public.payment_allocate(org,payment,jsonb_build_object('invoice_id',second,'amount','2','idempotency_key',gen_random_uuid()));
 perform pg_temp.fin_assert(private.payment_allocated(payment)=120,'one payment allocated across multiple invoices');
 perform pg_temp.fin_assert(public.finance_detail(org,'invoices',second)->>'effective_status'='paid','second invoice settled');
 perform pg_temp.fin_assert((select document_snapshot->>'unallocated'='120' from public.receipts where payment_id=payment),'later allocation does not rewrite receipt');
 perform pg_temp.fin_denied(format('select public.payment_record(%L,%L,%L)',org,c.id,jsonb_build_object('idempotency_key',gen_random_uuid(),'payment_date',current_date,'amount','10','method_id',method,'allocations',jsonb_build_array(jsonb_build_object('invoice_id',invoice,'amount','10','idempotency_key',gen_random_uuid())))),'invalid allocation rolls back entire payment');
 perform pg_temp.fin_assert((select count(*)=0 from public.payments where contract_id=c.id and amount='10'),'allocation rollback leaves no payment');
 schedule=public.payment_schedule_save(org,c.id,'{"label":"Variation payment","items":[{"label":"Additional amount","calculation_type":"remaining","value":"0"}]}');
 perform public.payment_schedule_activate(org,schedule,1);
 perform pg_temp.fin_assert((select expected_amount='150' from public.payment_schedule_items where schedule_id=schedule),'additive schedule reflects approved change');
 perform pg_temp.fin_assert((select expected_amount='100' from public.payment_schedule_items where contract_id=c.id and label='Booking'),'paid milestone unchanged after additive adjustment');
 perform pg_temp.fin_assert(public.finance_summary(org,c.id)->0->>'schedule_unallocated'='0','adjusted schedule reconciles');
 -- A second accepted baseline lets deletion verify the historical price directly.
 fresh=gen_random_uuid();
 insert into public.quotations(id,organization_id,customer_id,project_id,quotation_number) values(fresh,org,c.customer_id,c.project_id,'FINANCE-DELETE');
 insert into public.quotation_revisions(organization_id,quotation_id,project_id,revision_number,currency,valid_until,document_snapshot) select org,fresh,c.project_id,1,c.currency,current_date+30,document_snapshot from public.quotation_revisions where id=c.revision_id returning id into original;
 insert into public.quotation_items(organization_id,revision_id,project_id,snapshot) select org,original,c.project_id,snapshot from public.quotation_items where revision_id=c.revision_id;
 update public.quotation_revisions set status='issued',issued_at=now(),totals=private.quotation_totals(id,discount) where id=original;
 update public.quotations set status='issued',current_revision_id=original where id=fresh;
 input=public.quotation_share_manage(org,'create',jsonb_build_object('revision_id',original));perform public.public_quotation(input->>'token','respond','{"action":"approved","name":"Customer","acknowledged":true}');
 fresh=public.contract_create(org,original);select id into original from public.quotation_items where revision_id=original;
 co=pg_temp.fin_change(jsonb_build_object('action','save','contract_id',fresh,'reason','Remove original work','items',jsonb_build_array(jsonb_build_object('change_type','deletion','description','Remove wardrobe','reason','Customer removal','original_item_id',original,'pricing_type','manual','unit_rate','999999'))));
 perform pg_temp.fin_assert((select net_adjustment='-1000' from public.change_orders where id=co),'deletion uses contracted historical amount not submitted current rate');
 perform pg_temp.fin_change(jsonb_build_object('action','issue','contract_id',fresh,'id',co,'version',1));perform pg_temp.fin_change(jsonb_build_object('action','approve','contract_id',fresh,'id',co,'version',2,'evidence','Customer signed removal'));
 perform pg_temp.fin_assert(private.contract_value(fresh)=0,'full deletion can reduce contract to zero');
 co=pg_temp.fin_change(jsonb_build_object('action','save','contract_id',fresh,'reason','Invalid deduction','items',jsonb_build_array(jsonb_build_object('change_type','price_adjustment','description','Too much deduction','reason','Test deduction','pricing_type','manual','adjustment','-1'))));
 perform pg_temp.fin_denied(format('select pg_temp.fin_change(%L)',jsonb_build_object('action','issue','contract_id',fresh,'id',co,'version',1)),'negative contract value blocked');
 perform pg_temp.fin_change(jsonb_build_object('action','cancel','contract_id',fresh,'id',co,'version',1,'reason','Invalid draft withdrawn'));
 perform pg_temp.fin_assert((select status='cancelled' from public.change_orders where id=co),'draft change cancellation retained');
 perform public.contract_transition(org,fresh,1,'active');
 perform public.contract_transition(org,fresh,2,'completed');
 perform public.contract_transition(org,fresh,3,'closed','All commercial balances resolved');
 perform pg_temp.fin_assert((select status='closed' and closed_at is not null from public.contracts where id=fresh),'zero-value resolved contract closes with retained history');
 perform pg_temp.fin_denied(format('select public.payment_schedule_save(%L,%L,%L)',org,fresh,'{"label":"Closed","items":[{"label":"Invalid","calculation_type":"fixed","value":"1"}]}'),'closed contract rejects new schedule');
end$$;
create temporary table fin_foreign as select c.id contract_id,(select id from public.payments where contract_id=c.id limit 1) payment_id,(select id from public.invoices where contract_id=c.id limit 1) invoice_id from public.contracts c join public.quotations q on q.current_revision_id=c.revision_id where q.quotation_number='FINANCE-TEST';
grant select on fin_foreign to authenticated;
insert into public.organization_entitlements(organization_id,module_id,enabled,source) select 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',id,false,'manual' from public.modules where key='billing';
set local role authenticated;
select pg_temp.fin_denied('select public.finance_search(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''contracts'')','revoked billing entitlement blocks finance RPC');
select pg_temp.fin_assert((select count(*)=0 from public.contracts),'revoked billing entitlement hides finance rows');
reset role;
delete from public.organization_entitlements where organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and not enabled and module_id=(select id from public.modules where key='billing');
-- A different tenant Owner has all finance grants in that tenant only.
create temporary table fin_other(id uuid);
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',true);
insert into fin_other select public.create_organization(jsonb_build_object('name','Other finance tenant','slug','other-finance-'||gen_random_uuid(),'currency','INR','country','IN','timezone','Asia/Kolkata'));
insert into public.organization_entitlements(organization_id,module_id,enabled,source) select o.id,m.id,true,'manual' from fin_other o cross join public.modules m where m.key in ('billing','projects');
grant select on fin_other to authenticated;
set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';other uuid;target uuid;t text;begin
 select id into other from fin_other;
 select contract_id into target from fin_foreign;
 foreach t in array array['contracts','invoices','payments','payment_allocations','change_orders','receipts','organization_billing_settings'] loop
 perform pg_temp.fin_assert((public.finance_search(other,t)->>'total')::integer=0,'new tenant finance isolated: '||t);
 perform pg_temp.fin_denied(format('select public.finance_search(%L,%L)',org,t),'cross-tenant finance read denied: '||t);
 perform pg_temp.fin_denied(format('select public.finance_document(%L,%L,%L)',org,case when t in ('invoices','receipts','change_orders') then t else 'invoices' end,target),'cross-tenant document denied: '||t);end loop;
 perform pg_temp.fin_denied(format('select public.invoice_save(%L,%L,''{}'')',other,target),'cross-tenant invoice context rejected');
 perform pg_temp.fin_denied(format('select public.payment_allocate(%L,%L,%L)',other,(select payment_id from fin_foreign),jsonb_build_object('invoice_id',(select invoice_id from fin_foreign),'amount','1','idempotency_key',gen_random_uuid())),'cross-tenant payment allocation rejected');
end$$;
reset role;
rollback;
