-- Runs in the execution.sql fixture transaction, before its final rollback.
reset role;
delete from public.organization_entitlements where organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and not enabled and module_id in(select id from public.modules where key='billing');
set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';c uuid;p uuid;r uuid;t uuid;t2 uuid;m uuid;pkg uuid;v integer;template uuid;i uuid;i2 uuid;s uuid;h uuid;ht uuid;vendor uuid;wo uuid;wm uuid;doc jsonb;begin
 select id into c from public.contracts where revision_id in(select r.id from public.quotation_revisions r join public.quotations q on q.id=r.quotation_id where q.quotation_number='EXECUTION-TEST');
 p=public.operations_plan(org,'create',jsonb_build_object('contract_id',c));
 perform pg_temp.execution_assert(p=public.operations_plan(org,'create',jsonb_build_object('contract_id',c)),'plan creation retry returns same plan');
 select id into r from public.execution_plan_revisions where plan_id=p and status='draft';
 select project_id into c from public.execution_plans where id=p;
 pkg=public.operations_save(org,'work_packages',jsonb_build_object('project_id',c,'plan_id',p,'name','Installation'));
 m=public.operations_save(org,'project_milestones',jsonb_build_object('project_id',c,'plan_id',p,'name','Install'));
 t=public.operations_save(org,'project_tasks',jsonb_build_object('project_id',c,'plan_id',p,'work_package_id',pkg,'milestone_id',m,'title','Preparation','weight','2'));
 t2=public.operations_save(org,'project_tasks',jsonb_build_object('project_id',c,'plan_id',p,'milestone_id',m,'title','Installation'));
 perform public.operations_task(org,'dependency_add',jsonb_build_object('id',t2,'version',1,'predecessor_id',t));
 perform pg_temp.execution_denied(format('select public.operations_task(%L,''dependency_add'',%L)',org,jsonb_build_object('id',t,'version',1,'predecessor_id',t2)),'circular task dependency denied');
 perform pg_temp.execution_denied(format('select public.operations_task(%L,''task'',%L)',org,jsonb_build_object('id',t2,'version',2,'status','done')),'unfinished predecessor blocks completion');
 perform public.operations_plan(org,'approve',jsonb_build_object('id',r,'version',1));
 select snapshot into doc from public.execution_plan_revisions where id=r;
 perform public.operations_plan(org,'status',jsonb_build_object('id',p,'version',1,'status','in_progress'));
 perform pg_temp.execution_denied(format('select public.operations_task(%L,''task'',%L)',org,jsonb_build_object('id',t,'version',1,'status','blocked')),'blocked task requires reason');
 perform public.operations_task(org,'task',jsonb_build_object('id',t,'version',1,'status','blocked','reason','Waiting for materials'));
 perform pg_temp.execution_assert((select blocked_at is not null and blocked_by=auth.uid() from public.project_tasks where id=t),'blocked task stores actor and time');
 perform pg_temp.execution_denied(format('select public.operations_task(%L,''task'',%L)',org,jsonb_build_object('id',t,'version',2,'status','in_progress','completion_percentage','120')),'progress cannot exceed 100');
 perform public.operations_task(org,'task',jsonb_build_object('id',t,'version',2,'status','in_progress','completion_percentage','100'));
 perform pg_temp.execution_assert((select status='done' and completion_percentage='100' from public.project_tasks where id=t),'100 percent completes task');
 perform public.operations_task(org,'task',jsonb_build_object('id',t2,'version',2,'status','done'));
 perform public.operations_task(org,'milestone',jsonb_build_object('id',m,'version',1,'status','completed'));
 perform pg_temp.execution_assert((select snapshot=doc from public.execution_plan_revisions where id=r),'progress preserves approved plan snapshot');
 perform public.operations_plan(org,'revise',jsonb_build_object('id',p,'version',2));
 perform pg_temp.execution_assert((select count(*)=2 from public.execution_plan_revisions where plan_id=p),'plan revision preserves predecessor');
 select id into vendor from public.vendors where organization_id=org and status='active' order by id limit 1;
 perform public.operations_save(org,'vendor_execution_profiles',jsonb_build_object('vendor_id',vendor,'specialization','Installation'));
 wo=public.operations_work_order(org,'create',jsonb_build_object('plan_id',p,'vendor_id',vendor,'title','Installation','scope','Install project units','unit','hour','quantity','10','agreed_amount','1000'));
 perform public.operations_work_order(org,'issue',jsonb_build_object('id',wo,'version',1));
 wm=public.operations_work_order(org,'measure',jsonb_build_object('id',wo,'version',2,'quantity','4','note','Four measured hours'));
 perform public.operations_work_order(org,'verify',jsonb_build_object('id',wm,'version',1,'reason','Quantity checked'));
 perform public.operations_work_order(org,'certify',jsonb_build_object('id',wm,'version',2,'reason','Accepted measured work'));
 perform pg_temp.execution_assert((select amount='400' from public.work_measurement_costs where measurement_id=wm),'certified measurement carries proportional exact cost');
 perform pg_temp.execution_denied(format('select public.operations_work_order(%L,''measure'',%L)',org,jsonb_build_object('id',wo,'version',3,'quantity','7','note','Excess measurement')),'measurement cannot exceed remaining work');
 perform pg_temp.execution_denied(format('select public.operations_work_order(%L,''cancel'',%L)',org,jsonb_build_object('id',wo,'version',3,'reason','Cancel certified work')),'certified work prevents cancellation');
 perform public.operations_work_order(org,'progress',jsonb_build_object('id',wo,'version',3,'completed_percentage','100','accepted_percentage','100'));
 perform pg_temp.execution_assert((select status='completed' from public.subcontractor_work_orders where id=wo),'accepted subcontract progress completes work');
 template=public.operations_save(org,'inspection_templates','{"name":"Final acceptance","is_final":true,"mandatory":true,"checklist":[{"key":"finish","label":"Finish checked","required":true}]}');
 i=public.operations_inspection(org,'create',jsonb_build_object('project_id',c,'template_id',template,'inspector_id',auth.uid()));
 perform public.operations_inspection(org,'approve',jsonb_build_object('id',i,'version',1,'status','failed','results','[{"key":"finish","result":"fail","note":"Scratch"}]'::jsonb));
 s=public.operations_snag(org,'create',jsonb_build_object('project_id',c,'inspection_id',i,'title','Scratch','priority','critical'));
 perform public.operations_snag(org,'assign',jsonb_build_object('id',s,'version',1,'assigned_to',auth.uid()));
 perform public.operations_snag(org,'transition',jsonb_build_object('id',s,'version',2,'status','in_progress'));
 perform pg_temp.execution_denied(format('select public.operations_snag(%L,''transition'',%L)',org,jsonb_build_object('id',s,'version',3,'status','ready_for_review')),'snag review requires resolution evidence');
 perform public.operations_snag(org,'transition',jsonb_build_object('id',s,'version',3,'status','ready_for_review','resolution','Panel repaired'));
 perform public.operations_snag(org,'transition',jsonb_build_object('id',s,'version',4,'status','verified','verification','Repair checked'));
 perform public.operations_snag(org,'transition',jsonb_build_object('id',s,'version',5,'status','closed','verification','Accepted repair'));
 perform pg_temp.execution_assert((select count(*)=6 from public.project_execution_events where entity_id=s),'snag lifecycle appends six history events');
 i2=public.operations_inspection(org,'create',jsonb_build_object('project_id',c,'template_id',template,'predecessor_id',i,'inspector_id',auth.uid()));
 perform public.operations_plan(org,'status',jsonb_build_object('id',p,'version',3,'status','punch_list'));
 ht=public.operations_save(org,'handover_templates','{"name":"Handover","checklist":[{"key":"keys","label":"Keys delivered","required":true}]}');
 h=public.operations_handover(org,'create',jsonb_build_object('plan_id',p,'template_id',ht));
 perform pg_temp.execution_denied(format('select public.operations_handover(%L,''approve'',%L)',org,jsonb_build_object('id',h,'version',1,'results','[{"key":"keys","result":"pass"}]'::jsonb,'materials_review','Stock reconciled','commercial_review','Outstanding reviewed')),'pending final inspection blocks handover');
 perform public.operations_inspection(org,'approve',jsonb_build_object('id',i2,'version',1,'status','passed','results','[{"key":"finish","result":"pass","note":"Repaired"}]'::jsonb));
 perform public.operations_handover(org,'approve',jsonb_build_object('id',h,'version',1,'results','[{"key":"keys","result":"pass"}]'::jsonb,'materials_review','Stock reconciled','commercial_review','Outstanding reviewed','internal_notes','Private staff note','customer_notes','Keys delivered'));
 perform pg_temp.execution_assert((select status='handed_over' from public.execution_plans where id=p),'handover transitions physical plan');
 perform pg_temp.execution_assert((select not(document_snapshot ? 'internal_notes') and document_snapshot->>'notes'='Keys delivered' from public.handover_records where id=h),'handover customer snapshot excludes staff notes');
 perform pg_temp.execution_assert(public.operations_document(org,'handover',h)->>'notes'='Keys delivered' and not(public.operations_document(org,'handover',h)::text like '%Private staff note%'),'handover PDF projection strips internal review notes');
 perform pg_temp.execution_assert(public.operations_document(org,'inspection',i2)->>'result'='passed','final inspection document preserves result');
 perform pg_temp.execution_assert((public.operations_options(org,'project_tasks',c)->'rows'->0->>'label') is not null,'task choices provide a readable label');
 perform pg_temp.execution_denied(format('select public.operations_handover(%L,''approve'',%L)',org,jsonb_build_object('id',h,'version',1,'results','[]'::jsonb)),'duplicate handover cannot finalize twice');
 perform public.operations_plan(org,'status',jsonb_build_object('id',p,'version',5,'status','completed'));
 perform pg_temp.execution_assert((select status='completed' from public.execution_plans where id=p),'operational completion succeeds after approved handover');
end$$;
reset role;
select pg_temp.execution_denied('update public.execution_plan_revisions set snapshot=''{}'' where status=''approved''','approved plan history rejects privileged edits');
select pg_temp.execution_denied('delete from public.project_inspections','inspection history rejects deletion');
select pg_temp.execution_denied('update public.handover_records set internal_notes=''changed'' where status=''approved''','approved handover rejects edits');
rollback;

