do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';revision uuid;line uuid;project uuid;variant uuid;pr uuid;rfq uuid;vendor uuid;quote uuid;po uuid;receipt uuid;receipt_item uuid;store uuid;site uuid;lot uuid;request uuid;item uuid;tx uuid;issue uuid;payload jsonb;v integer;begin
 select l.id,l.revision_id,r.project_id,l.variant_id into line,revision,project,variant from public.execution_estimate_lines l join public.execution_estimate_revisions r on r.id=l.revision_id where r.status='approved' and l.cost_kind='material' and l.description='Carcass and shelves';
 if line is null then raise exception 'Material fixture missing';end if;
 select id into vendor from public.vendors where organization_id=org and status='active' order by id limit 1;
 pr=public.execution_requisition_create(org,jsonb_build_object('idempotency_key',gen_random_uuid(),'revision_id',revision,'delivery_location','Central store','sources',jsonb_build_array(jsonb_build_object('line_id',line,'quantity','6'))));
 perform public.execution_requisition_transition(org,pr,1,'submit');
 perform public.execution_requisition_transition(org,pr,2,'approve');
 rfq=public.execution_rfq_create(org,jsonb_build_object('requisition_id',pr,'idempotency_key',gen_random_uuid(),'vendor_ids',jsonb_build_array(vendor),'items',jsonb_build_array(jsonb_build_object('requisition_item_id',(select id from public.purchase_requisition_items where requisition_id=pr),'quantity','6'))));
 perform public.execution_rfq_transition(org,rfq,1,'issue');
 quote=public.execution_vendor_quote_save(org,jsonb_build_object('idempotency_key',gen_random_uuid(),'rfq_id',rfq,'vendor_id',vendor,'reference','OPS-STOCK','currency','INR','valid_until',current_date+30,'freight','0','items',jsonb_build_array(jsonb_build_object('rfq_item_id',(select id from public.rfq_items where rfq_id=rfq),'quantity','6','unit_price','100','discount','0','tax_mode','exclusive','tax_components','[]'::jsonb))));
 perform public.execution_vendor_quote_transition(org,quote,1,'record');
 po=public.execution_po_create(org,jsonb_build_object('quote_id',quote,'idempotency_key',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('quote_item_id',(select id from public.vendor_quote_items where quote_id=quote),'quantity','6'))));
 perform public.execution_po_transition(org,po,1,'issue');
 receipt=public.execution_receipt_record(org,jsonb_build_object('po_id',po,'idempotency_key',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('po_item_id',(select id from public.purchase_order_items where po_id=po),'received_quantity','6','accepted_quantity','6','rejected_quantity','0'))));
 select id into receipt_item from public.goods_receipt_items where receipt_id=receipt;
 store=public.operations_save(org,'inventory_locations','{"name":"Central store","kind":"central_store"}');
 site=public.operations_save(org,'inventory_locations',jsonb_build_object('name','Project site','kind','project_site','site_project_id',project));
 payload=jsonb_build_object('project_id',project,'receipt_item_id',receipt_item,'destination_location_id',store,'reason','Accepted delivery','idempotency_key',gen_random_uuid());
 tx=public.operations_stock(org,'purchase_receipt',payload);
 perform pg_temp.execution_assert(tx=public.operations_stock(org,'purchase_receipt',payload),'receipt stock posting is idempotent');
 perform pg_temp.execution_denied(format('select public.operations_stock(%L,''purchase_receipt'',%L)',org,payload||jsonb_build_object('idempotency_key',gen_random_uuid())),'receipt cannot be posted twice with a new retry key');
 select id into lot from public.inventory_lots where receipt_item_id=receipt_item;
 request=public.operations_issue_request(org,'create',jsonb_build_object('project_id',project,'source_location_id',store,'destination_location_id',site,'reason','Install materials','items',jsonb_build_array(jsonb_build_object('variant_id',variant,'unit','sheet','quantity','3'))));
 perform public.operations_issue_request(org,'submit',jsonb_build_object('id',request,'version',1));
 select id into item from public.material_issue_request_items where request_id=request;
 perform public.operations_issue_request(org,'approve',jsonb_build_object('id',request,'version',2,'items',jsonb_build_array(jsonb_build_object('id',item,'approved_quantity','2'))));
 payload=jsonb_build_object('project_id',project,'lot_id',lot,'source_location_id',store,'destination_location_id',site,'request_item_id',item,'quantity','2','reason','First delivery','idempotency_key',gen_random_uuid());
 tx=public.operations_stock(org,'issue_to_site',payload);
 perform pg_temp.execution_assert((select status='partially_issued' from public.material_issue_requests where id=request),'partial issue retains remaining demand');
 perform pg_temp.execution_denied(format('select public.operations_issue_request(%L,''approve'',%L)',org,jsonb_build_object('id',request,'version',4,'items',jsonb_build_array(jsonb_build_object('id',item,'approved_quantity','1')))),'additional approval cannot revoke previously approved quantity');
 perform public.operations_issue_request(org,'approve',jsonb_build_object('id',request,'version',4,'items',jsonb_build_array(jsonb_build_object('id',item,'approved_quantity','3'))));
 issue=public.operations_stock(org,'issue_to_site',payload||jsonb_build_object('quantity','1','idempotency_key',gen_random_uuid()));
 perform pg_temp.execution_assert((select status='fully_issued' from public.material_issue_requests where id=request),'remaining issue completes request');
 perform pg_temp.execution_denied(format('select public.operations_stock(%L,''consumption'',%L)',org,jsonb_build_object('project_id',project,'lot_id',lot,'source_location_id',site,'quantity','4','reason','Invalid consumption','idempotency_key',gen_random_uuid())),'consumption above available stock rolls back');
 perform public.operations_stock(org,'consumption',jsonb_build_object('project_id',project,'lot_id',lot,'source_location_id',site,'quantity','2','reason','Installed material','idempotency_key',gen_random_uuid()));
 perform public.operations_stock(org,'return_from_site',jsonb_build_object('project_id',project,'lot_id',lot,'source_location_id',site,'destination_location_id',store,'original_transaction_id',issue,'quantity','0.5','reason','Unused material','idempotency_key',gen_random_uuid()));
 tx=public.operations_stock(org,'scrap',jsonb_build_object('project_id',project,'lot_id',lot,'source_location_id',site,'quantity','0.2','reason','Cutting offcuts','idempotency_key',gen_random_uuid()));
 perform pg_temp.execution_assert((select sum(quantity::numeric)=0.3 from public.inventory_movements where lot_id=lot and location_id=site),'site ledger distinguishes consumption return and scrap');
 perform pg_temp.execution_assert((select sum(quantity::numeric)=3.5 from public.inventory_movements where lot_id=lot and location_id=store),'return restores central stock');
 perform public.operations_stock(org,'reversal',jsonb_build_object('project_id',project,'original_transaction_id',tx,'reason','Incorrect scrap record','idempotency_key',gen_random_uuid()));
 perform pg_temp.execution_assert((select sum(quantity::numeric)=0.5 from public.inventory_movements where lot_id=lot and location_id=site),'reversal restores stock without deleting history');
 perform pg_temp.execution_denied(format('select public.operations_stock(%L,''reversal'',%L)',org,jsonb_build_object('project_id',project,'original_transaction_id',tx,'reason','Duplicate reversal','idempotency_key',gen_random_uuid())),'second reversal is rejected');
 perform public.operations_stock(org,'damage',jsonb_build_object('project_id',project,'lot_id',lot,'source_location_id',site,'quantity','0.1','reason','Broken edge','idempotency_key',gen_random_uuid()));
 perform public.operations_stock(org,'count',jsonb_build_object('project_id',project,'lot_id',lot,'source_location_id',store,'physical_quantity','3','reason','Physical stock count','idempotency_key',gen_random_uuid()));
 perform pg_temp.execution_assert((select sum(quantity::numeric)=3 from public.inventory_movements where lot_id=lot and location_id=store),'stock count posts adjustment through ledger');
 perform pg_temp.execution_assert((select system_quantity='3.5' and physical_quantity='3' from public.inventory_counts where lot_id=lot),'count retains expected and observed quantities');
 perform pg_temp.execution_assert((select x->>'consumed'='2' and x->>'at_site'='0.4' and x->>'at_store'='3' and x->>'planned_purchase'='6' from jsonb_array_elements(public.operations_materials(org,project)->'rows')x where x->>'variant_id'=variant::text),'material report reconciles source estimate stock and explicit consumption');
 perform pg_temp.execution_assert(public.operations_costs(org,project)#>>'{rows,0,consumed_material_cost}'='200','consumption cost follows accepted receipt lot');
 perform pg_temp.execution_assert(jsonb_array_length(public.operations_document(org,'consumption',project)->'rows')>0,'authorized consumption report contains material rows');
 perform pg_temp.execution_assert(public.operations_document(org,'material_issue',issue)->>'kind'='material_issue','issued material has protected document projection');
end$$;

