reset role;
-- Give a test member only the Site template, then explicitly assign one project.
delete from public.membership_roles where membership_id in(select id from public.organization_memberships where organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and user_id='22222222-2222-4222-8222-222222222222');
insert into public.membership_roles(organization_id,membership_id,role_id) select m.organization_id,m.id,r.id from public.organization_memberships m join public.roles r on r.organization_id=m.organization_id where m.organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and m.user_id='22222222-2222-4222-8222-222222222222' and r.key='site_supervisor';
set local request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';
set local role authenticated;
select pg_temp.execution_assert((select count(*)=0 from public.project_tasks),'unassigned Site member cannot read tasks');
select pg_temp.execution_assert((select count(*)=0 from public.inventory_movements),'unassigned Site member cannot read stock');
select pg_temp.execution_denied('select public.operations_stock(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''adjustment'',''{"reason":"Unauthorized adjustment","idempotency_key":"77777777-7777-4777-8777-777777777777","quantity":"1"}'')','Site cannot adjust inventory');
reset role;
insert into public.project_execution_members(organization_id,project_id,user_id) select organization_id,project_id,'22222222-2222-4222-8222-222222222222' from public.execution_plans;
set local role authenticated;
select pg_temp.execution_assert((select count(*)>0 from public.project_tasks),'assigned Site member can read project tasks');
select pg_temp.execution_assert((select count(*)>0 from public.inventory_lots),'assigned Site member can select delivered receipt lots');
select pg_temp.execution_assert((select count(*)=0 from public.inventory_lot_costs),'Site receipt-lot access does not expose costs');
select pg_temp.execution_assert((select count(*)=0 from public.subcontractor_work_order_costs),'Site cannot read subcontract prices');
select pg_temp.execution_denied('select public.operations_search(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''inventory_lot_costs'')','Site cannot bypass cost policy through search');
select pg_temp.execution_denied('select public.operations_search(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''contracts'')','operations search rejects nonallowlisted tables');
select pg_temp.execution_assert((public.operations_balances('dddddddd-dddd-4ddd-8ddd-dddddddddddd')->>'total')::integer=1,'Site balance query only exposes assigned site location');
reset role;
set local request.jwt.claim.sub='60000000-0000-4000-8000-000000000001';
set local role authenticated;
select pg_temp.execution_assert((select count(*)=0 from public.project_tasks),'other tenant cannot read project tasks');
select pg_temp.execution_assert((select count(*)=0 from public.inventory_transactions),'other tenant cannot read inventory transactions');
select pg_temp.execution_assert((select count(*)=0 from public.handover_records),'other tenant cannot read handover');
select pg_temp.execution_assert((select count(*)=0 from public.project_inspections),'other tenant cannot read inspections');
select pg_temp.execution_assert((select count(*)=0 from public.project_snags),'other tenant cannot read snags');
select pg_temp.execution_denied('select public.operations_search(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''project_tasks'')','other tenant cannot query operations search');
reset role;
set local role anon;
select pg_temp.execution_denied('select * from public.inventory_movements','anonymous users cannot read inventory');
select pg_temp.execution_denied('select public.operations_search(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''project_tasks'')','anonymous users cannot call operations search');
reset role;
