begin;
create function pg_temp.website_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end$$;
create function pg_temp.website_denied(command text,label text) returns void language plpgsql as $$begin begin execute command;exception when insufficient_privilege or check_violation or invalid_parameter_value or serialization_failure or unique_violation then raise notice 'PASS: %',label;return;end;raise exception 'FAIL: %',label;end$$;
create function pg_temp.website_proof(site uuid,v integer,doc jsonb,restore uuid default null) returns jsonb language sql as $$select jsonb_build_object('keyId','phase8-test','purpose','website.publish','organizationId','dddddddd-dddd-4ddd-8ddd-dddddddddddd','websiteId',site,'version',v,'expiresAt',now()+interval '5 minutes','restoreId',restore,'build',jsonb_build_object('schemaVersion',1,'document',doc,'artifacts','[]'::jsonb));$$;
create function pg_temp.website_signature(body jsonb) returns text language sql security definer set search_path='' as $$select encode(extensions.hmac(convert_to(body::text,'UTF8'),convert_to('phase8-test-key-not-a-production-secret-123456','UTF8'),'sha256'),'hex');$$;
insert into private.website_build_keys(key_id,secret) values('phase8-test',convert_to('phase8-test-key-not-a-production-secret-123456','UTF8')) on conflict(key_id) do update set secret=excluded.secret,active=true;
insert into public.organization_entitlements(organization_id,module_id,enabled,source,configuration) select 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',id,true,'manual','{"custom_domain":true,"custom_code":true,"developer_mode":true,"sites":20,"pages":100,"forms":true}' from public.modules where key='website' on conflict(organization_id,module_id,source) do update set enabled=true,configuration=excluded.configuration;
update public.website_platform_settings set base_domain='sites.example',managed_subdomain_tls=true where id;
select set_config('test.website_document',/*DOCUMENT*/::text,true);
set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';
set local role authenticated;
do $$declare org uuid='dddddddd-dddd-4ddd-8ddd-dddddddddddd';site uuid;other uuid;publication uuid;restored uuid;doc jsonb=current_setting('test.website_document')::jsonb;proof jsonb;domain uuid;form jsonb;v integer;result jsonb;begin
 site=public.website_create(org,'Website test','phase8-test',doc);perform set_config('test.website_id',site::text,true);
 perform pg_temp.website_assert(public.website_read(org,site)->>'name'='Website test','website author can read own draft');
 perform pg_temp.website_assert(public.website_public('phase8-test.sites.example') is null,'draft website is not public');
 perform pg_temp.website_denied(format('select document from public.websites where id=%L',site),'raw draft and code column denied');
 perform pg_temp.website_denied(format('select public.website_create(%L,''Collision'',''phase8-test'',%L)',org,doc),'website slug collision denied');
 proof=pg_temp.website_proof(site,1,doc);
 perform pg_temp.website_denied(format('select public.website_publish(%L,%L,1,%L,''forged'',''Invalid'')',org,site,proof::text),'unsigned publish denied');
 publication=public.website_publish(org,site,1,proof::text,pg_temp.website_signature(proof),'First publication');perform set_config('test.website_version',publication::text,true);
 perform pg_temp.website_assert(public.website_public('phase8-test.sites.example')->>'version'=publication::text,'published hostname resolves current immutable version');
 doc=jsonb_set(doc,'{pages,0,nodes,0,props,text}','"Version two draft"');
 v=public.website_save(org,site,2,'pages',doc->'pages');
 perform pg_temp.website_assert(v=3,'website draft increments optimistic version');
 perform pg_temp.website_assert(public.website_public('phase8-test.sites.example')->'build'->'document'->'pages'->0->'nodes'->0->'props'->>'text'='Version one','website draft does not replace public version');
 perform pg_temp.website_denied(format('select public.website_save(%L,%L,2,''pages'',%L)',org,site,doc->'pages'),'stale draft save denied');
 proof=pg_temp.website_proof(site,3,doc);restored=public.website_publish(org,site,3,proof::text,pg_temp.website_signature(proof),'Second publication');
 perform pg_temp.website_assert(restored<>publication,'publishing creates a new version');
 proof=pg_temp.website_proof(site,4,current_setting('test.website_document')::jsonb,publication);restored=public.website_publish(org,site,4,proof::text,pg_temp.website_signature(proof),'Restored version one',publication);
 perform pg_temp.website_assert((select count(*)=3 from public.website_versions where website_id=site),'restore preserves all previous versions');
 perform pg_temp.website_assert(public.website_public('phase8-test.sites.example')->'build'->'document'->'pages'->0->'nodes'->0->'props'->>'text'='Version one','restore publishes original content as new version');
 perform pg_temp.website_assert(public.website_public('unknown.sites.example') is null,'unknown hostname cannot enumerate a website');
 domain=public.website_domain_add(org,site,'studio.example.org');perform set_config('test.website_domain',domain::text,true);
 perform pg_temp.website_assert(public.website_public('studio.example.org') is null,'unverified custom domain does not resolve');
 perform pg_temp.website_denied(format('select public.website_domain_check(%L,%L,''{}'',''browser-claim'')',org,domain),'browser cannot claim DNS verification');
 proof=jsonb_build_object('keyId','phase8-test','purpose','website.domain','organizationId',org,'domainId',domain,'hostname','studio.example.org','challenge',(select challenge from public.website_domains where id=domain),'dns',true,'tls',false,'expiresAt',now()+interval '5 minutes');
 perform pg_temp.website_assert(public.website_domain_check(org,domain,proof::text,pg_temp.website_signature(proof))='verified','DNS verification does not imply TLS readiness');
 perform pg_temp.website_assert(public.website_public('studio.example.org') is null,'verified domain without HTTPS stays unavailable');
 proof=jsonb_set(proof,'{tls}','true');perform public.website_domain_check(org,domain,proof::text,pg_temp.website_signature(proof));
 perform pg_temp.website_assert(public.website_public('studio.example.org')->>'version'=restored::text,'attested DNS and HTTPS activate custom domain');
 perform public.website_domain_remove(org,domain,3);perform pg_temp.website_assert(public.website_public('studio.example.org') is null,'removed domain no longer resolves');
 perform public.website_prepare_crm(org,site);
 form='{"id":"consultation","name":"Consultation","enabled":true,"confirmation":"Thank you for your enquiry","fields":[{"key":"name","label":"Name","type":"text","required":true,"mapping":"name","options":[]},{"key":"phone","label":"Phone","type":"phone","required":true,"mapping":"phone","options":[]},{"key":"consent","label":"Consent","type":"consent","required":true,"mapping":"consent","options":[]}]}'::jsonb;
 doc=current_setting('test.website_document')::jsonb;doc=jsonb_set(doc,'{forms}',jsonb_build_array(form));doc=jsonb_set(doc,'{pages,0,nodes}',doc->'pages'->0->'nodes'||'[ {"id":"lead","type":"lead_form","props":{"form":"consultation"},"style":{},"tablet":{},"mobile":{},"children":[]} ]'::jsonb);
 proof=pg_temp.website_proof(site,5,doc);perform public.website_publish(org,site,5,proof::text,pg_temp.website_signature(proof),'Enquiry form');
 perform pg_temp.website_denied($q$select public.website_submit_lead('phase8-test.sites.example','/','consultation','{"name":"Visitor","phone":"+919876543210","consent":false}')$q$,'website enquiry requires consent');
 result=public.website_submit_lead('phase8-test.sites.example','/','consultation','{"name":"Website visitor","phone":"+91 98765 43210","consent":true}');
 perform pg_temp.website_assert(result->>'accepted'='true' and not result ? 'id','public form returns confirmation without CRM identifier');
 perform pg_temp.website_assert((select count(*)=1 from public.leads where organization_id=org and phone_normalized='+919876543210'),'website creates canonical CRM lead');
 perform public.website_submit_lead('phase8-test.sites.example','/','consultation','{"name":"Repeat enquiry","phone":"+919876543210","consent":true}');
 perform pg_temp.website_assert((select count(*)=1 from public.leads where organization_id=org and phone_normalized='+919876543210'),'website duplicate detection reuses canonical lead');
 perform pg_temp.website_assert((select count(*)=2 from public.lead_activities where organization_id=org and metadata->>'website'=site::text and metadata->>'consent'='true'),'website activity retains source and consent');
 perform public.website_submit_lead('phase8-test.sites.example','/','consultation','{"name":"Bot","phone":"+919876543211","consent":true}','spam');
 perform pg_temp.website_assert(not exists(select 1 from public.leads where organization_id=org and phone_normalized='+919876543211'),'honeypot does not create CRM leads');
 perform pg_temp.website_denied($q$select public.website_submit_lead('phase8-test.sites.example','/private','consultation','{"name":"Visitor","phone":"+919876543210","consent":true}')$q$,'form must belong to the published page');
 perform public.website_submit_lead('phase8-test.sites.example','/','consultation','{"name":"Different visitor","phone":"+919876543219","consent":true}');
 perform pg_temp.website_assert((select count(*)=1 from public.leads where organization_id=org and phone_normalized='+919876543219'),'distinct visitor does not merge into an unrelated lead');
 perform public.website_grant_developer(org,site,'33333333-3333-4333-8333-333333333333');
end$$;
reset role;
update public.website_platform_settings set disabled_components='["heading"]' where id;
select pg_temp.website_assert(public.website_public('phase8-test.sites.example') is null,'platform component disable blocks incompatible public snapshot');
update public.website_platform_settings set disabled_components='[]' where id;
select pg_temp.website_assert(public.website_public('phase8-test.sites.example') is not null,'restoring component policy restores valid snapshot');
update private.website_form_limits set hits=60 where website_id=current_setting('test.website_id')::uuid;
set local role anon;
select pg_temp.website_assert(public.website_submit_lead('phase8-test.sites.example','/','consultation','{"name":"Limited","phone":"+919876543218","consent":true}')->>'accepted'='false','public rate limit rejects requests after the site quota');
reset role;
delete from public.membership_roles where membership_id in(select id from public.organization_memberships where organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and user_id='33333333-3333-4333-8333-333333333333') and role_id not in(select id from public.roles where key='website_developer');
set local request.jwt.claim.sub='33333333-3333-4333-8333-333333333333';set local role authenticated;
select pg_temp.website_assert(public.website_read('dddddddd-dddd-4ddd-8ddd-dddddddddddd',current_setting('test.website_id')::uuid)->>'name'='Website test','assigned website developer can read website');
select pg_temp.website_assert(not private.has_permission('dddddddd-dddd-4ddd-8ddd-dddddddddddd','contract.view') and not private.has_permission('dddddddd-dddd-4ddd-8ddd-dddddddddddd','billing.view') and not private.has_permission('dddddddd-dddd-4ddd-8ddd-dddddddddddd','customer.view'),'website developer denied finance');
select pg_temp.website_assert((select count(*)=0 from public.invoices),'website developer cannot select invoices');
select pg_temp.website_denied('select public.website_read(''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'','''||current_setting('test.website_id')||''')','cross-tenant website access denied');
reset role;
update public.website_members set active=false where website_id=current_setting('test.website_id')::uuid and user_id='33333333-3333-4333-8333-333333333333';
set local role authenticated;
select pg_temp.website_denied('select public.website_read(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'','''||current_setting('test.website_id')||''')','website assignment revocation is immediate');
reset role;set local request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';set local role authenticated;
select public.website_status('dddddddd-dddd-4ddd-8ddd-dddddddddddd',current_setting('test.website_id')::uuid,6,'unpublished');
select pg_temp.website_assert(public.website_public('phase8-test.sites.example') is null,'unpublished website no longer resolves');
reset role;
select pg_temp.website_denied('update public.website_versions set summary=''tampered'' where id='''||current_setting('test.website_version')||'''','published version rejects privileged destructive edits');
update public.organization_entitlements set enabled=false where organization_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd' and module_id in(select id from public.modules where key='website');
set local role authenticated;
select pg_temp.website_denied('select public.website_read(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'','''||current_setting('test.website_id')||''')','website entitlement revocation blocks management');
select pg_temp.website_assert(public.has_entitlement('dddddddd-dddd-4ddd-8ddd-dddddddddddd','projects'),'Website disabled leaves Projects enabled');
reset role;set local role anon;
select pg_temp.website_denied('select id from public.websites','anonymous direct website table reads denied');
select pg_temp.website_denied('select public.website_read(''dddddddd-dddd-4ddd-8ddd-dddddddddddd'','''||current_setting('test.website_id')||''')','anonymous draft RPC denied');
reset role;rollback;
